  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkd;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-12
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkbillVO extends SuperVO {
           
             public UFDate dbilldate;
             public String vbillno;
             public String accountcode;
             public String pk_corp;
             public String pk_fkfy;
             public String pk_deptdoc;
             public String khyh;
             public String vlastbilltype;
             public String voperatorid;
             public String pk_jbr;
             public String vapprovenote;
             public UFDate dapprovedate;
             public String pk_billtype;
             public Integer vbillstatus;
             public String pk_cust2;
             public String vlastbillid;
             public String vapproveid;
             public String vsourcebilltype;
             public UFDateTime tmodifytime;
             public String pk_busitype;
             public String vsourcebillid;
             public String cmodifyid;
             public String pk_fkbill;
             public String pk_manager;
             public UFDateTime ts;
             public Integer dr;
             
             
            
             public static final String  DBILLDATE="dbilldate";   
             public static final String  VBILLNO="vbillno";   
             public static final String  ACCOUNTCODE="accountcode";   
             public static final String  PK_CORP="pk_corp";   
             public static final String  PK_FKFY="pk_fkfy";   
             public static final String  PK_DEPTDOC="pk_deptdoc";   
             public static final String  KHYH="khyh";   
             public static final String  VLASTBILLTYPE="vlastbilltype";   
             public static final String  VOPERATORID="voperatorid";   
             public static final String  PK_JBR="pk_jbr";   
             public static final String  VAPPROVENOTE="vapprovenote";   
             public static final String  DAPPROVEDATE="dapprovedate";   
             public static final String  PK_BILLTYPE="pk_billtype";   
             public static final String  VBILLSTATUS="vbillstatus";   
             public static final String  PK_CUST2="pk_cust2";   
             public static final String  VLASTBILLID="vlastbillid";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  VSOURCEBILLTYPE="vsourcebilltype";   
             public static final String  TMODIFYTIME="tmodifytime";   
             public static final String  PK_BUSITYPE="pk_busitype";   
             public static final String  VSOURCEBILLID="vsourcebillid";   
             public static final String  CMODIFYID="cmodifyid";   
             public static final String  PK_FKBILL="pk_fkbill";   
             public static final String  PK_MANAGER="pk_manager";   
      
    
        /**
	   * 属性dbilldate的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDate
	   */
	 public UFDate getDbilldate() {
		 return dbilldate;
	  }   
	  
     /**
	   * 属性dbilldate的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDbilldate UFDate
	   */
	public void setDbilldate(UFDate newDbilldate) {
		
		dbilldate = newDbilldate;
	 } 	  
       
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性accountcode的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getAccountcode() {
		 return accountcode;
	  }   
	  
     /**
	   * 属性accountcode的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newAccountcode String
	   */
	public void setAccountcode(String newAccountcode) {
		
		accountcode = newAccountcode;
	 } 	  
       
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性pk_fkfy的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_fkfy() {
		 return pk_fkfy;
	  }   
	  
     /**
	   * 属性pk_fkfy的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_fkfy String
	   */
	public void setPk_fkfy(String newPk_fkfy) {
		
		pk_fkfy = newPk_fkfy;
	 } 	  
       
        /**
	   * 属性pk_deptdoc的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_deptdoc() {
		 return pk_deptdoc;
	  }   
	  
     /**
	   * 属性pk_deptdoc的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_deptdoc String
	   */
	public void setPk_deptdoc(String newPk_deptdoc) {
		
		pk_deptdoc = newPk_deptdoc;
	 } 	  
       
        /**
	   * 属性khyh的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getKhyh() {
		 return khyh;
	  }   
	  
     /**
	   * 属性khyh的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newKhyh String
	   */
	public void setKhyh(String newKhyh) {
		
		khyh = newKhyh;
	 } 	  
       
        /**
	   * 属性vlastbilltype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVlastbilltype() {
		 return vlastbilltype;
	  }   
	  
     /**
	   * 属性vlastbilltype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVlastbilltype String
	   */
	public void setVlastbilltype(String newVlastbilltype) {
		
		vlastbilltype = newVlastbilltype;
	 } 	  
       
        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }   
	  
     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {
		
		voperatorid = newVoperatorid;
	 } 	  
       
        /**
	   * 属性pk_jbr的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_jbr() {
		 return pk_jbr;
	  }   
	  
     /**
	   * 属性pk_jbr的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_jbr String
	   */
	public void setPk_jbr(String newPk_jbr) {
		
		pk_jbr = newPk_jbr;
	 } 	  
       
        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }   
	  
     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {
		
		vapprovenote = newVapprovenote;
	 } 	  
       
        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }   
	  
     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {
		
		dapprovedate = newDapprovedate;
	 } 	  
       
        /**
	   * 属性pk_billtype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_billtype() {
		 return pk_billtype;
	  }   
	  
     /**
	   * 属性pk_billtype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_billtype String
	   */
	public void setPk_billtype(String newPk_billtype) {
		
		pk_billtype = newPk_billtype;
	 } 	  
       
        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }   
	  
     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {
		
		vbillstatus = newVbillstatus;
	 } 	  
       
        /**
	   * 属性pk_cust2的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_cust2() {
		 return pk_cust2;
	  }   
	  
     /**
	   * 属性pk_cust2的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_cust2 String
	   */
	public void setPk_cust2(String newPk_cust2) {
		
		pk_cust2 = newPk_cust2;
	 } 	  
       
        /**
	   * 属性vlastbillid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVlastbillid() {
		 return vlastbillid;
	  }   
	  
     /**
	   * 属性vlastbillid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVlastbillid String
	   */
	public void setVlastbillid(String newVlastbillid) {
		
		vlastbillid = newVlastbillid;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性vsourcebilltype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVsourcebilltype() {
		 return vsourcebilltype;
	  }   
	  
     /**
	   * 属性vsourcebilltype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVsourcebilltype String
	   */
	public void setVsourcebilltype(String newVsourcebilltype) {
		
		vsourcebilltype = newVsourcebilltype;
	 } 	  
       
        /**
	   * 属性tmodifytime的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDateTime
	   */
	 public UFDateTime getTmodifytime() {
		 return tmodifytime;
	  }   
	  
     /**
	   * 属性tmodifytime的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newTmodifytime UFDateTime
	   */
	public void setTmodifytime(UFDateTime newTmodifytime) {
		
		tmodifytime = newTmodifytime;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性vsourcebillid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVsourcebillid() {
		 return vsourcebillid;
	  }   
	  
     /**
	   * 属性vsourcebillid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVsourcebillid String
	   */
	public void setVsourcebillid(String newVsourcebillid) {
		
		vsourcebillid = newVsourcebillid;
	 } 	  
       
        /**
	   * 属性cmodifyid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getCmodifyid() {
		 return cmodifyid;
	  }   
	  
     /**
	   * 属性cmodifyid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newCmodifyid String
	   */
	public void setCmodifyid(String newCmodifyid) {
		
		cmodifyid = newCmodifyid;
	 } 	  
       
        /**
	   * 属性pk_fkbill的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_fkbill() {
		 return pk_fkbill;
	  }   
	  
     /**
	   * 属性pk_fkbill的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_fkbill String
	   */
	public void setPk_fkbill(String newPk_fkbill) {
		
		pk_fkbill = newPk_fkbill;
	 } 	  
       
        /**
	   * 属性pk_manager的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_manager() {
		 return pk_manager;
	  }   
	  
     /**
	   * 属性pk_manager的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_manager String
	   */
	public void setPk_manager(String newPk_manager) {
		
		pk_manager = newPk_manager;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2013-10-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fkbill == null) {
			errFields.add(new String("pk_fkbill"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkbill";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkbill";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-12
	  */
	public DhFkbillVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-12
	 * @param newPk_fkbill 主键值
	 */
	 public DhFkbillVO(String newPk_fkbill) {
		
		// 为主键字段赋值:
		 pk_fkbill = newPk_fkbill;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkbill;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-12
	  * @param newPk_fkbill  String    
	  */
	 public void setPrimaryKey(String newPk_fkbill) {
				
				pk_fkbill = newPk_fkbill; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkbill"; 
				
	 }

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	} 
} 
