  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.htlogo;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-6
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class ConLogoBVO extends SuperVO {
           
             public String pk_conlogo;
             public String vggxh;
             public String vdef4;
             public String invcode;
             public String vdef7;
             public String vdef3;
             public String vdef9;
             public UFDate dghsj;
             public String vdef8;
             public String pk_danw;
             public String vmen;
             public String pk_invbasdoc;
             public String vdef2;
             public UFDouble djprice;
             public UFDouble djetotal;
             public String vdef6;
             public String vdef10;
             public UFDouble nnumber;
             public String vdef1;
             public String vdef5;
             public String pk_conlogo_b;
             public UFDateTime ts;
             public Integer dr;
             public String invname;
             public String lengtht;
            
             
			   
       
   	public UFDate getDghsj() {
				return dghsj;
			}

			public void setDghsj(UFDate dghsj) {
				this.dghsj = dghsj;
			}

			public UFDouble getDjetotal() {
				return djetotal;
			}

			public void setDjetotal(UFDouble djetotal) {
				this.djetotal = djetotal;
			}

			public UFDouble getDjprice() {
				return djprice;
			}

			public void setDjprice(UFDouble djprice) {
				this.djprice = djprice;
			}

			public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public String getInvcode() {
				return invcode;
			}

			public void setInvcode(String invcode) {
				this.invcode = invcode;
			}

			public String getInvname() {
				return invname;
			}

			public void setInvname(String invname) {
				this.invname = invname;
			}

			public String getLengtht() {
				return lengtht;
			}

			public void setLengtht(String lengtht) {
				this.lengtht = lengtht;
			}

			public UFDouble getNnumber() {
				return nnumber;
			}

			public void setNnumber(UFDouble nnumber) {
				this.nnumber = nnumber;
			}

			public String getPk_conlogo() {
				return pk_conlogo;
			}

			public void setPk_conlogo(String pk_conlogo) {
				this.pk_conlogo = pk_conlogo;
			}

			public String getPk_conlogo_b() {
				return pk_conlogo_b;
			}

			public void setPk_conlogo_b(String pk_conlogo_b) {
				this.pk_conlogo_b = pk_conlogo_b;
			}

			public String getPk_danw() {
				return pk_danw;
			}

			public void setPk_danw(String pk_danw) {
				this.pk_danw = pk_danw;
			}

			public String getPk_invbasdoc() {
				return pk_invbasdoc;
			}

			public void setPk_invbasdoc(String pk_invbasdoc) {
				this.pk_invbasdoc = pk_invbasdoc;
			}

			public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

			public String getVdef1() {
				return vdef1;
			}

			public void setVdef1(String vdef1) {
				this.vdef1 = vdef1;
			}

			public String getVdef10() {
				return vdef10;
			}

			public void setVdef10(String vdef10) {
				this.vdef10 = vdef10;
			}

			public String getVdef2() {
				return vdef2;
			}

			public void setVdef2(String vdef2) {
				this.vdef2 = vdef2;
			}

			public String getVdef3() {
				return vdef3;
			}

			public void setVdef3(String vdef3) {
				this.vdef3 = vdef3;
			}

			public String getVdef4() {
				return vdef4;
			}

			public void setVdef4(String vdef4) {
				this.vdef4 = vdef4;
			}

			public String getVdef5() {
				return vdef5;
			}

			public void setVdef5(String vdef5) {
				this.vdef5 = vdef5;
			}

			public String getVdef6() {
				return vdef6;
			}

			public void setVdef6(String vdef6) {
				this.vdef6 = vdef6;
			}

			public String getVdef7() {
				return vdef7;
			}

			public void setVdef7(String vdef7) {
				this.vdef7 = vdef7;
			}

			public String getVdef8() {
				return vdef8;
			}

			public void setVdef8(String vdef8) {
				this.vdef8 = vdef8;
			}

			public String getVdef9() {
				return vdef9;
			}

			public void setVdef9(String vdef9) {
				this.vdef9 = vdef9;
			}

			public String getVggxh() {
				return vggxh;
			}

			public void setVggxh(String vggxh) {
				this.vggxh = vggxh;
			}

			public String getVmen() {
				return vmen;
			}

			public void setVmen(String vmen) {
				this.vmen = vmen;
			}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_conlogo";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_conlogo_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_conlogo_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-6
	  */
	public ConLogoBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-6
	 * @param newPk_conlogo_b 主键值
	 */
	 public ConLogoBVO(String newPk_conlogo_b) {
		
		// 为主键字段赋值:
		 pk_conlogo_b = newPk_conlogo_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-6
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_conlogo_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-6
	  * @param newPk_conlogo_b  String    
	  */
	 public void setPrimaryKey(String newPk_conlogo_b) {
				
				pk_conlogo_b = newPk_conlogo_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-6
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_conlogo_b"; 
				
	 } 
} 
