  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkd;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-12
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkbillBVO extends SuperVO {
           
             public String vlastbillrowid;
             public String vdef4;
             public String vdef7;
             public String ctcode;
             public String vmen;
             public String vdef2;
             public UFDouble dkfje;
             public String vsourcebilltype;
             public String vsourcebillrowid;
             public String vdef1;
             public UFDouble dfkbl;
             public UFDouble dctjetotal;
             public String vsourcebillheadid;
             public String vprojectname;
             public UFDouble dfkje;
             public UFDouble dsqfkje;
             public String vlastbilltype;
             public String vdef3;
             public String vdef9;
             public String vdef8;
             public String vlastbillheadid;
             public String vfkcontext;
             public String pk_fkbill_b;
             public String vdef6;
             public String vdef10;
             public String vdef5;
             public String pk_fkbill;
             public UFDateTime ts;
             public Integer dr;
             public String pk_deptdoc;
             public String pk_fzr;
             public String vlastbillid;
            
             public String getVlastbillid() {
				return vlastbillid;
			}

			public void setVlastbillid(String vlastbillid) {
				this.vlastbillid = vlastbillid;
			}

			public static final String  VLASTBILLROWID="vlastbillrowid";   
             public static final String  VDEF4="vdef4";   
             public static final String  VDEF7="vdef7";   
             public static final String  CTCODE="ctcode";   
             public static final String  VMEN="vmen";   
             public static final String  VDEF2="vdef2";   
             public static final String  DKFJE="dkfje";   
             public static final String  VSOURCEBILLTYPE="vsourcebilltype";   
             public static final String  VSOURCEBILLROWID="vsourcebillrowid";   
             public static final String  VDEF1="vdef1";   
             public static final String  DFKBL="dfkbl";   
             public static final String  DCTJETOTAL="dctjetotal";   
             public static final String  VSOURCEBILLHEADID="vsourcebillheadid";   
             public static final String  VPROJECTNAME="vprojectname";   
             public static final String  DFKJE="dfkje";   
             public static final String  VLASTBILLTYPE="vlastbilltype";   
             public static final String  VDEF3="vdef3";   
             public static final String  VDEF9="vdef9";   
             public static final String  VDEF8="vdef8";   
             public static final String  VLASTBILLHEADID="vlastbillheadid";   
             public static final String  VFKCONTEXT="vfkcontext";   
             public static final String  PK_FKBILL_B="pk_fkbill_b";   
             public static final String  VDEF6="vdef6";   
             public static final String  VDEF10="vdef10";   
             public static final String  VDEF5="vdef5";   
             public static final String  PK_FKBILL="pk_fkbill";   
      
    
        /**
	   * 属性vlastbillrowid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVlastbillrowid() {
		 return vlastbillrowid;
	  }   
	  
     /**
	   * 属性vlastbillrowid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVlastbillrowid String
	   */
	public void setVlastbillrowid(String newVlastbillrowid) {
		
		vlastbillrowid = newVlastbillrowid;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef7 String
	   */
	public void setVdef7(String newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性ctcode的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getCtcode() {
		 return ctcode;
	  }   
	  
     /**
	   * 属性ctcode的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newCtcode String
	   */
	public void setCtcode(String newCtcode) {
		
		ctcode = newCtcode;
	 } 	  
       
        /**
	   * 属性vmen的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVmen() {
		 return vmen;
	  }   
	  
     /**
	   * 属性vmen的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVmen String
	   */
	public void setVmen(String newVmen) {
		
		vmen = newVmen;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性dkfje的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDouble
	   */
	 public UFDouble getDkfje() {
		 return dkfje;
	  }   
	  
     /**
	   * 属性dkfje的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDkfje UFDouble
	   */
	public void setDkfje(UFDouble newDkfje) {
		
		dkfje = newDkfje;
	 } 	  
       
        /**
	   * 属性vsourcebilltype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVsourcebilltype() {
		 return vsourcebilltype;
	  }   
	  
     /**
	   * 属性vsourcebilltype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVsourcebilltype String
	   */
	public void setVsourcebilltype(String newVsourcebilltype) {
		
		vsourcebilltype = newVsourcebilltype;
	 } 	  
       
        /**
	   * 属性vsourcebillrowid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVsourcebillrowid() {
		 return vsourcebillrowid;
	  }   
	  
     /**
	   * 属性vsourcebillrowid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVsourcebillrowid String
	   */
	public void setVsourcebillrowid(String newVsourcebillrowid) {
		
		vsourcebillrowid = newVsourcebillrowid;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性dfkbl的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDouble
	   */
	 public UFDouble getDfkbl() {
		 return dfkbl;
	  }   
	  
     /**
	   * 属性dfkbl的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDfkbl UFDouble
	   */
	public void setDfkbl(UFDouble newDfkbl) {
		
		dfkbl = newDfkbl;
	 } 	  
       
        /**
	   * 属性dctjetotal的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDouble
	   */
	 public UFDouble getDctjetotal() {
		 return dctjetotal;
	  }   
	  
     /**
	   * 属性dctjetotal的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDctjetotal UFDouble
	   */
	public void setDctjetotal(UFDouble newDctjetotal) {
		
		dctjetotal = newDctjetotal;
	 } 	  
       
        /**
	   * 属性vsourcebillheadid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVsourcebillheadid() {
		 return vsourcebillheadid;
	  }   
	  
     /**
	   * 属性vsourcebillheadid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVsourcebillheadid String
	   */
	public void setVsourcebillheadid(String newVsourcebillheadid) {
		
		vsourcebillheadid = newVsourcebillheadid;
	 } 	  
       
        /**
	   * 属性vprojectname的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVprojectname() {
		 return vprojectname;
	  }   
	  
     /**
	   * 属性vprojectname的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVprojectname String
	   */
	public void setVprojectname(String newVprojectname) {
		
		vprojectname = newVprojectname;
	 } 	  
       
        /**
	   * 属性dfkje的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return UFDouble
	   */
	 public UFDouble getDfkje() {
		 return dfkje;
	  }   
	  
     /**
	   * 属性dfkje的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newDfkje UFDouble
	   */
	public void setDfkje(UFDouble newDfkje) {
		
		dfkje = newDfkje;
	 } 	  
       
        /**
	   * 属性vlastbilltype的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVlastbilltype() {
		 return vlastbilltype;
	  }   
	  
     /**
	   * 属性vlastbilltype的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVlastbilltype String
	   */
	public void setVlastbilltype(String newVlastbilltype) {
		
		vlastbilltype = newVlastbilltype;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef9 String
	   */
	public void setVdef9(String newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef8 String
	   */
	public void setVdef8(String newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性vlastbillheadid的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVlastbillheadid() {
		 return vlastbillheadid;
	  }   
	  
     /**
	   * 属性vlastbillheadid的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVlastbillheadid String
	   */
	public void setVlastbillheadid(String newVlastbillheadid) {
		
		vlastbillheadid = newVlastbillheadid;
	 } 	  
       
        /**
	   * 属性vfkcontext的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVfkcontext() {
		 return vfkcontext;
	  }   
	  
     /**
	   * 属性vfkcontext的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVfkcontext String
	   */
	public void setVfkcontext(String newVfkcontext) {
		
		vfkcontext = newVfkcontext;
	 } 	  
       
        /**
	   * 属性pk_fkbill_b的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_fkbill_b() {
		 return pk_fkbill_b;
	  }   
	  
     /**
	   * 属性pk_fkbill_b的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_fkbill_b String
	   */
	public void setPk_fkbill_b(String newPk_fkbill_b) {
		
		pk_fkbill_b = newPk_fkbill_b;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef6 String
	   */
	public void setVdef6(String newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef10 String
	   */
	public void setVdef10(String newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性pk_fkbill的Getter方法.
	   *
	   * 创建日期:2013-10-12
	   * @return String
	   */
	 public String getPk_fkbill() {
		 return pk_fkbill;
	  }   
	  
     /**
	   * 属性pk_fkbill的Setter方法.
	   *
	   * 创建日期:2013-10-12
	   * @param newPk_fkbill String
	   */
	public void setPk_fkbill(String newPk_fkbill) {
		
		pk_fkbill = newPk_fkbill;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2013-10-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fkbill_b == null) {
			errFields.add(new String("pk_fkbill_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_fkbill";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkbill_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkbill_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-12
	  */
	public DhFkbillBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-12
	 * @param newPk_fkbill_b 主键值
	 */
	 public DhFkbillBVO(String newPk_fkbill_b) {
		
		// 为主键字段赋值:
		 pk_fkbill_b = newPk_fkbill_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkbill_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-12
	  * @param newPk_fkbill_b  String    
	  */
	 public void setPrimaryKey(String newPk_fkbill_b) {
				
				pk_fkbill_b = newPk_fkbill_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkbill_b"; 
				
	 }

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public UFDouble getDsqfkje() {
		return dsqfkje;
	}

	public void setDsqfkje(UFDouble dsqfkje) {
		this.dsqfkje = dsqfkje;
	}

	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	public void setPk_deptdoc(String pk_deptdoc) {
		this.pk_deptdoc = pk_deptdoc;
	}

	public String getPk_fzr() {
		return pk_fzr;
	}

	public void setPk_fzr(String pk_fzr) {
		this.pk_fzr = pk_fzr;
	} 
} 
