  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkgx;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-1-3
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkgxVO extends SuperVO {
           
             public String pk_fkgx;
             public String pk_user1;
             public String pk_deptdoc;
             public String pk_corp;
             public Integer is_manager;
             
             
            
             public static final String  PK_FKGX="pk_fkgx";   
             public static final String  PK_USER1="pk_user1";   
             public static final String  PK_DEPTDOC="pk_deptdoc";   
             public static final String  PK_CORP = "pk_corp";
             public static final String  IS_MANAGER = "is_manager";
      	  
       
             
             
             
        public Integer getIs_manager() {
				return is_manager;
			}

			public void setIs_manager(Integer is_manager) {
				this.is_manager = is_manager;
			}

			public String getPk_corp() {
				return pk_corp;
			}

			public void setPk_corp(String pk_corp) {
				this.pk_corp = pk_corp;
			}

		/**
	   * 属性pk_fkgx的Getter方法.
	   *
	   * 创建日期:2014-1-3
	   * @return String
	   */
	 public String getPk_fkgx() {
		 return pk_fkgx;
	  }   
	  
     /**
	   * 属性pk_fkgx的Setter方法.
	   *
	   * 创建日期:2014-1-3
	   * @param newPk_fkgx String
	   */
	public void setPk_fkgx(String newPk_fkgx) {
		
		pk_fkgx = newPk_fkgx;
	 } 	  
       
        /**
	   * 属性pk_user1的Getter方法.
	   *
	   * 创建日期:2014-1-3
	   * @return String
	   */
	 public String getPk_user1() {
		 return pk_user1;
	  }   
	  
     /**
	   * 属性pk_user1的Setter方法.
	   *
	   * 创建日期:2014-1-3
	   * @param newPk_user1 String
	   */
	public void setPk_user1(String newPk_user1) {
		
		pk_user1 = newPk_user1;
	 } 	  
       
        /**
	   * 属性pk_deptdoc的Getter方法.
	   *
	   * 创建日期:2014-1-3
	   * @return String
	   */
	 public String getPk_deptdoc() {
		 return pk_deptdoc;
	  }   
	  
     /**
	   * 属性pk_deptdoc的Setter方法.
	   *
	   * 创建日期:2014-1-3
	   * @param newPk_deptdoc String
	   */
	public void setPk_deptdoc(String newPk_deptdoc) {
		
		pk_deptdoc = newPk_deptdoc;
	 } 	  	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-1-3
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fkgx == null) {
			errFields.add(new String("pk_fkgx"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-1-3
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-1-3
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkgx";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-1-3
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkgx";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-1-3
	  */
	public DhFkgxVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-1-3
	 * @param newPk_fkgx 主键值
	 */
	 public DhFkgxVO(String newPk_fkgx) {
		
		// 为主键字段赋值:
		 pk_fkgx = newPk_fkgx;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-3
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkgx;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-3
	  * @param newPk_fkgx  String    
	  */
	 public void setPrimaryKey(String newPk_fkgx) {
				
				pk_fkgx = newPk_fkgx; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-1-3
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkgx"; 
				
	 } 
} 
