/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.dh.httk;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2013-12-22
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class DhHttkVO extends SuperVO {

	public String ctname3;
	public String ctcode19;
	public String pk_corp;
	public String ctname15;
	public String ctname11;
	public String pk_cttype;
	public String ctcode18;
	public String ctcode3;
	public String voperatorid;
	public String ctname10;
	public String ctname17;
	public String ctname13;
	public String ctcode6;
	public String ctname9;
	public String ctname20;
	public String ctname2;
	public String ctcode17;
	public String ctname18;
	public String ctcode5;
	public String ctcode11;
	public String ctname1;
	public String ctname19;
	public UFDate dbilldate;
	public String vbillno;
	public String ctcode4;
	public String ctcode12;
	public String ctname4;
	public String ctcode7;
	public String ctcode15;
	public String ctname6;
	public String pk_httk;
	public String ctname16;
	public String ctname14;
	public String ctcode2;
	public String ctcode13;
	public String ctname7;
	public String ctcode20;
	public String ctcode14;
	public String ctcode10;
	public String ctcode1;
	public String ctcode8;
	public String ctname8;
	public String ctname12;
	public String ctcode16;
	public String ctname5;

	public String ctcode9;
	public Integer httype;
	public String tkmbname;

	public String getTkmbname() {
		return tkmbname;
	}

	public void setTkmbname(String tkmbname) {
		this.tkmbname = tkmbname;
	}

	public static final String CTNAME3 = "ctname3";
	public static final String CTCODE19 = "ctcode19";
	public static final String PK_CORP = "pk_corp";
	public static final String CTNAME15 = "ctname15";
	public static final String CTNAME11 = "ctname11";
	public static final String PK_CTTYPE = "pk_cttype";
	public static final String CTCODE18 = "ctcode18";
	public static final String CTCODE3 = "ctcode3";
	public static final String VOPERATORID = "voperatorid";
	public static final String CTNAME10 = "ctname10";
	public static final String CTNAME17 = "ctname17";
	public static final String CTNAME13 = "ctname13";
	public static final String CTCODE6 = "ctcode6";
	public static final String CTNAME9 = "ctname9";
	public static final String CTNAME20 = "ctname20";
	public static final String CTNAME2 = "ctname2";
	public static final String CTCODE17 = "ctcode17";
	public static final String CTNAME18 = "ctname18";
	public static final String CTCODE5 = "ctcode5";
	public static final String CTCODE11 = "ctcode11";
	public static final String CTNAME1 = "ctname1";
	public static final String CTNAME19 = "ctname19";
	public static final String DBILLDATE = "dbilldate";
	public static final String VBILLNO = "vbillno";
	public static final String CTCODE4 = "ctcode4";
	public static final String CTCODE12 = "ctcode12";
	public static final String CTNAME4 = "ctname4";
	public static final String CTCODE7 = "ctcode7";
	public static final String CTCODE15 = "ctcode15";
	public static final String CTNAME6 = "ctname6";
	public static final String PK_HTTK = "pk_httk";
	public static final String CTNAME16 = "ctname16";
	public static final String CTNAME14 = "ctname14";
	public static final String CTCODE2 = "ctcode2";
	public static final String CTCODE13 = "ctcode13";
	public static final String CTNAME7 = "ctname7";
	public static final String CTCODE20 = "ctcode20";
	public static final String CTCODE14 = "ctcode14";
	public static final String CTCODE10 = "ctcode10";
	public static final String CTCODE1 = "ctcode1";
	public static final String CTCODE8 = "ctcode8";
	public static final String CTNAME8 = "ctname8";
	public static final String CTNAME12 = "ctname12";
	public static final String CTCODE16 = "ctcode16";
	public static final String CTNAME5 = "ctname5";
	public static final String CTCODE9 = "ctcode9";

	public Integer getHttype() {
		return httype;
	}

	public void setHttype(Integer httype) {
		this.httype = httype;
	}

	/**
	 * 属性ctname3的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname3() {
		return ctname3;
	}

	/**
	 * 属性ctname3的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname3
	 *            String
	 */
	public void setCtname3(String newCtname3) {

		ctname3 = newCtname3;
	}

	/**
	 * 属性ctcode19的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode19() {
		return ctcode19;
	}

	/**
	 * 属性ctcode19的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode19
	 *            String
	 */
	public void setCtcode19(String newCtcode19) {

		ctcode19 = newCtcode19;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性ctname15的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname15() {
		return ctname15;
	}

	/**
	 * 属性ctname15的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname15
	 *            String
	 */
	public void setCtname15(String newCtname15) {

		ctname15 = newCtname15;
	}

	/**
	 * 属性ctname11的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname11() {
		return ctname11;
	}

	/**
	 * 属性ctname11的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname11
	 *            String
	 */
	public void setCtname11(String newCtname11) {

		ctname11 = newCtname11;
	}

	/**
	 * 属性pk_cttype的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getPk_cttype() {
		return pk_cttype;
	}

	/**
	 * 属性pk_cttype的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newPk_cttype
	 *            String
	 */
	public void setPk_cttype(String newPk_cttype) {

		pk_cttype = newPk_cttype;
	}

	/**
	 * 属性ctcode18的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode18() {
		return ctcode18;
	}

	/**
	 * 属性ctcode18的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode18
	 *            String
	 */
	public void setCtcode18(String newCtcode18) {

		ctcode18 = newCtcode18;
	}

	/**
	 * 属性ctcode3的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode3() {
		return ctcode3;
	}

	/**
	 * 属性ctcode3的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode3
	 *            String
	 */
	public void setCtcode3(String newCtcode3) {

		ctcode3 = newCtcode3;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性ctname10的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname10() {
		return ctname10;
	}

	/**
	 * 属性ctname10的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname10
	 *            String
	 */
	public void setCtname10(String newCtname10) {

		ctname10 = newCtname10;
	}

	/**
	 * 属性ctname17的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname17() {
		return ctname17;
	}

	/**
	 * 属性ctname17的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname17
	 *            String
	 */
	public void setCtname17(String newCtname17) {

		ctname17 = newCtname17;
	}

	/**
	 * 属性ctname13的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname13() {
		return ctname13;
	}

	/**
	 * 属性ctname13的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname13
	 *            String
	 */
	public void setCtname13(String newCtname13) {

		ctname13 = newCtname13;
	}

	/**
	 * 属性ctcode6的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode6() {
		return ctcode6;
	}

	/**
	 * 属性ctcode6的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode6
	 *            String
	 */
	public void setCtcode6(String newCtcode6) {

		ctcode6 = newCtcode6;
	}

	/**
	 * 属性ctname9的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname9() {
		return ctname9;
	}

	/**
	 * 属性ctname9的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname9
	 *            String
	 */
	public void setCtname9(String newCtname9) {

		ctname9 = newCtname9;
	}

	/**
	 * 属性ctname20的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname20() {
		return ctname20;
	}

	/**
	 * 属性ctname20的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname20
	 *            String
	 */
	public void setCtname20(String newCtname20) {

		ctname20 = newCtname20;
	}

	/**
	 * 属性ctname2的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname2() {
		return ctname2;
	}

	/**
	 * 属性ctname2的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname2
	 *            String
	 */
	public void setCtname2(String newCtname2) {

		ctname2 = newCtname2;
	}

	/**
	 * 属性ctcode17的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode17() {
		return ctcode17;
	}

	/**
	 * 属性ctcode17的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode17
	 *            String
	 */
	public void setCtcode17(String newCtcode17) {

		ctcode17 = newCtcode17;
	}

	/**
	 * 属性ctname18的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname18() {
		return ctname18;
	}

	/**
	 * 属性ctname18的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname18
	 *            String
	 */
	public void setCtname18(String newCtname18) {

		ctname18 = newCtname18;
	}

	/**
	 * 属性ctcode5的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode5() {
		return ctcode5;
	}

	/**
	 * 属性ctcode5的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode5
	 *            String
	 */
	public void setCtcode5(String newCtcode5) {

		ctcode5 = newCtcode5;
	}

	/**
	 * 属性ctcode11的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode11() {
		return ctcode11;
	}

	/**
	 * 属性ctcode11的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode11
	 *            String
	 */
	public void setCtcode11(String newCtcode11) {

		ctcode11 = newCtcode11;
	}

	/**
	 * 属性ctname1的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname1() {
		return ctname1;
	}

	/**
	 * 属性ctname1的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname1
	 *            String
	 */
	public void setCtname1(String newCtname1) {

		ctname1 = newCtname1;
	}

	/**
	 * 属性ctname19的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname19() {
		return ctname19;
	}

	/**
	 * 属性ctname19的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname19
	 *            String
	 */
	public void setCtname19(String newCtname19) {

		ctname19 = newCtname19;
	}

	/**
	 * 属性dbilldate的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return UFDate
	 */
	public UFDate getDbilldate() {
		return dbilldate;
	}

	/**
	 * 属性dbilldate的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newDbilldate
	 *            UFDate
	 */
	public void setDbilldate(UFDate newDbilldate) {

		dbilldate = newDbilldate;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newVbillno
	 *            String
	 */
	public void setVbillno(String newVbillno) {

		vbillno = newVbillno;
	}

	/**
	 * 属性ctcode4的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode4() {
		return ctcode4;
	}

	/**
	 * 属性ctcode4的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode4
	 *            String
	 */
	public void setCtcode4(String newCtcode4) {

		ctcode4 = newCtcode4;
	}

	/**
	 * 属性ctcode12的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode12() {
		return ctcode12;
	}

	/**
	 * 属性ctcode12的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode12
	 *            String
	 */
	public void setCtcode12(String newCtcode12) {

		ctcode12 = newCtcode12;
	}

	/**
	 * 属性ctname4的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname4() {
		return ctname4;
	}

	/**
	 * 属性ctname4的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname4
	 *            String
	 */
	public void setCtname4(String newCtname4) {

		ctname4 = newCtname4;
	}

	/**
	 * 属性ctcode7的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode7() {
		return ctcode7;
	}

	/**
	 * 属性ctcode7的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode7
	 *            String
	 */
	public void setCtcode7(String newCtcode7) {

		ctcode7 = newCtcode7;
	}

	/**
	 * 属性ctcode15的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode15() {
		return ctcode15;
	}

	/**
	 * 属性ctcode15的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode15
	 *            String
	 */
	public void setCtcode15(String newCtcode15) {

		ctcode15 = newCtcode15;
	}

	/**
	 * 属性ctname6的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname6() {
		return ctname6;
	}

	/**
	 * 属性ctname6的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname6
	 *            String
	 */
	public void setCtname6(String newCtname6) {

		ctname6 = newCtname6;
	}

	/**
	 * 属性pk_httk的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getPk_httk() {
		return pk_httk;
	}

	/**
	 * 属性pk_httk的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newPk_httk
	 *            String
	 */
	public void setPk_httk(String newPk_httk) {

		pk_httk = newPk_httk;
	}

	/**
	 * 属性ctname16的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname16() {
		return ctname16;
	}

	/**
	 * 属性ctname16的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname16
	 *            String
	 */
	public void setCtname16(String newCtname16) {

		ctname16 = newCtname16;
	}

	/**
	 * 属性ctname14的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname14() {
		return ctname14;
	}

	/**
	 * 属性ctname14的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname14
	 *            String
	 */
	public void setCtname14(String newCtname14) {

		ctname14 = newCtname14;
	}

	/**
	 * 属性ctcode2的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode2() {
		return ctcode2;
	}

	/**
	 * 属性ctcode2的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode2
	 *            String
	 */
	public void setCtcode2(String newCtcode2) {

		ctcode2 = newCtcode2;
	}

	/**
	 * 属性ctcode13的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode13() {
		return ctcode13;
	}

	/**
	 * 属性ctcode13的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode13
	 *            String
	 */
	public void setCtcode13(String newCtcode13) {

		ctcode13 = newCtcode13;
	}

	/**
	 * 属性ctname7的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname7() {
		return ctname7;
	}

	/**
	 * 属性ctname7的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname7
	 *            String
	 */
	public void setCtname7(String newCtname7) {

		ctname7 = newCtname7;
	}

	/**
	 * 属性ctcode20的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode20() {
		return ctcode20;
	}

	/**
	 * 属性ctcode20的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode20
	 *            String
	 */
	public void setCtcode20(String newCtcode20) {

		ctcode20 = newCtcode20;
	}

	/**
	 * 属性ctcode14的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode14() {
		return ctcode14;
	}

	/**
	 * 属性ctcode14的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode14
	 *            String
	 */
	public void setCtcode14(String newCtcode14) {

		ctcode14 = newCtcode14;
	}

	/**
	 * 属性ctcode10的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode10() {
		return ctcode10;
	}

	/**
	 * 属性ctcode10的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode10
	 *            String
	 */
	public void setCtcode10(String newCtcode10) {

		ctcode10 = newCtcode10;
	}

	/**
	 * 属性ctcode1的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode1() {
		return ctcode1;
	}

	/**
	 * 属性ctcode1的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode1
	 *            String
	 */
	public void setCtcode1(String newCtcode1) {

		ctcode1 = newCtcode1;
	}

	/**
	 * 属性ctcode8的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode8() {
		return ctcode8;
	}

	/**
	 * 属性ctcode8的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode8
	 *            String
	 */
	public void setCtcode8(String newCtcode8) {

		ctcode8 = newCtcode8;
	}

	/**
	 * 属性ctname8的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname8() {
		return ctname8;
	}

	/**
	 * 属性ctname8的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname8
	 *            String
	 */
	public void setCtname8(String newCtname8) {

		ctname8 = newCtname8;
	}

	/**
	 * 属性ctname12的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname12() {
		return ctname12;
	}

	/**
	 * 属性ctname12的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname12
	 *            String
	 */
	public void setCtname12(String newCtname12) {

		ctname12 = newCtname12;
	}

	/**
	 * 属性ctcode16的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode16() {
		return ctcode16;
	}

	/**
	 * 属性ctcode16的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode16
	 *            String
	 */
	public void setCtcode16(String newCtcode16) {

		ctcode16 = newCtcode16;
	}

	/**
	 * 属性ctname5的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtname5() {
		return ctname5;
	}

	/**
	 * 属性ctname5的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtname5
	 *            String
	 */
	public void setCtname5(String newCtname5) {

		ctname5 = newCtname5;
	}

	/**
	 * 属性ctcode9的Getter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getCtcode9() {
		return ctcode9;
	}

	/**
	 * 属性ctcode9的Setter方法.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newCtcode9
	 *            String
	 */
	public void setCtcode9(String newCtcode9) {

		ctcode9 = newCtcode9;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_httk == null) {
			errFields.add(new String("pk_httk"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2013-12-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2013-12-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_httk";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2013-12-22
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "dh_httk";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2013-12-22
	 */
	public DhHttkVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newPk_httk
	 *            主键值
	 */
	public DhHttkVO(String newPk_httk) {

		// 为主键字段赋值:
		pk_httk = newPk_httk;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_httk;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @param newPk_httk
	 *            String
	 */
	public void setPrimaryKey(String newPk_httk) {

		pk_httk = newPk_httk;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2013-12-22
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "dh_httk";

	}
}
