  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.cttreebill;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-6
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhContractB1VO extends SuperVO {
           
             public String pk_contract;
             public String vdef4;
             public String vdef7;
             public UFDateTime dsjfktime;
             public String vdef3;
             public String vdef9;
             public UFDateTime dplandtime;
             public String vdef8;
             public String vfkname;
             public String vmen;
             public String vkpmen;
             public String vdef2;
             public UFDouble dfkjetotal;
             public String pk_contract_b1;
             public String vdef6;
             public String vdef10;
             public String pk_vfkid;
             public String vdef1;
             public String vdef5;
             public UFDateTime ts;
             public Integer dr;
            
             public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

			public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public static final String  PK_CONTRACT="pk_contract";   
             public static final String  VDEF4="vdef4";   
             public static final String  VDEF7="vdef7";   
             public static final String  DSJFKTIME="dsjfktime";   
             public static final String  VDEF3="vdef3";   
             public static final String  VDEF9="vdef9";   
             public static final String  DPLANDTIME="dplandtime";   
             public static final String  VDEF8="vdef8";   
             public static final String  VFKNAME="vfkname";   
             public static final String  VMEN="vmen";   
             public static final String  VKPMEN="vkpmen";   
             public static final String  VDEF2="vdef2";   
             public static final String  DFKJETOTAL="dfkjetotal";   
             public static final String  PK_CONTRACT_B1="pk_contract_b1";   
             public static final String  VDEF6="vdef6";   
             public static final String  VDEF10="vdef10";   
             public static final String  PK_VFKID="pk_vfkid";   
             public static final String  VDEF1="vdef1";   
             public static final String  VDEF5="vdef5";   
      
    
        /**
	   * 属性pk_contract的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getPk_contract() {
		 return pk_contract;
	  }   
	  
     /**
	   * 属性pk_contract的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newPk_contract String
	   */
	public void setPk_contract(String newPk_contract) {
		
		pk_contract = newPk_contract;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef7 String
	   */
	public void setVdef7(String newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性dsjfktime的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return UFDateTime
	   */
	 public UFDateTime getDsjfktime() {
		 return dsjfktime;
	  }   
	  
     /**
	   * 属性dsjfktime的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newDsjfktime UFDateTime
	   */
	public void setDsjfktime(UFDateTime newDsjfktime) {
		
		dsjfktime = newDsjfktime;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef9 String
	   */
	public void setVdef9(String newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性dplandtime的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return UFDateTime
	   */
	 public UFDateTime getDplandtime() {
		 return dplandtime;
	  }   
	  
     /**
	   * 属性dplandtime的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newDplandtime UFDateTime
	   */
	public void setDplandtime(UFDateTime newDplandtime) {
		
		dplandtime = newDplandtime;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef8 String
	   */
	public void setVdef8(String newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性vfkname的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVfkname() {
		 return vfkname;
	  }   
	  
     /**
	   * 属性vfkname的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVfkname String
	   */
	public void setVfkname(String newVfkname) {
		
		vfkname = newVfkname;
	 } 	  
       
        /**
	   * 属性vmen的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVmen() {
		 return vmen;
	  }   
	  
     /**
	   * 属性vmen的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVmen String
	   */
	public void setVmen(String newVmen) {
		
		vmen = newVmen;
	 } 	  
       
        /**
	   * 属性vkpmen的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVkpmen() {
		 return vkpmen;
	  }   
	  
     /**
	   * 属性vkpmen的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVkpmen String
	   */
	public void setVkpmen(String newVkpmen) {
		
		vkpmen = newVkpmen;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性dfkjetotal的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return UFDouble
	   */
	 public UFDouble getDfkjetotal() {
		 return dfkjetotal;
	  }   
	  
     /**
	   * 属性dfkjetotal的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newDfkjetotal UFDouble
	   */
	public void setDfkjetotal(UFDouble newDfkjetotal) {
		
		dfkjetotal = newDfkjetotal;
	 } 	  
       
        /**
	   * 属性pk_contract_b1的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getPk_contract_b1() {
		 return pk_contract_b1;
	  }   
	  
     /**
	   * 属性pk_contract_b1的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newPk_contract_b1 String
	   */
	public void setPk_contract_b1(String newPk_contract_b1) {
		
		pk_contract_b1 = newPk_contract_b1;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef6 String
	   */
	public void setVdef6(String newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef10 String
	   */
	public void setVdef10(String newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性pk_vfkid的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getPk_vfkid() {
		 return pk_vfkid;
	  }   
	  
     /**
	   * 属性pk_vfkid的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newPk_vfkid String
	   */
	public void setPk_vfkid(String newPk_vfkid) {
		
		pk_vfkid = newPk_vfkid;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2013-10-6
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2013-10-6
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2013-10-6
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_contract_b1 == null) {
			errFields.add(new String("pk_contract_b1"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_contract";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_contract_b1";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-6
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_contract_b1";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-6
	  */
	public DhContractB1VO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-6
	 * @param newPk_contract_b1 主键值
	 */
	 public DhContractB1VO(String newPk_contract_b1) {
		
		// 为主键字段赋值:
		 pk_contract_b1 = newPk_contract_b1;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-6
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_contract_b1;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-6
	  * @param newPk_contract_b1  String    
	  */
	 public void setPrimaryKey(String newPk_contract_b1) {
				
				pk_contract_b1 = newPk_contract_b1; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-6
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_contract_b1"; 
				
	 } 
} 
