  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.jcInfo.invInfo;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-4-23
 * @author author
 * @version Your Project 1.0
 */
     public class BgInvEntity extends SuperVO {
           
             public String pk_bginv;
             public Integer bg_status;
             public String pk_invbasdoc;
             public String og_invno;
             public String og_invname;
             public String og_invcl;
             public String pk_invcl;
             public String inv_no;
             public String inv_name;
             public String remark;
             public String voperid;
             public UFDate voperdate;
             public String vapproveid;
             public UFDate vapprovedate;
             public String pk_dept;
             public String pk_corp;
             public Integer dr;
             public UFDateTime ts;
            
             public static final String  BG_STATUS="bg_status";   
             public static final String  PK_INVBASDOC="pk_invbasdoc";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  PK_INVCL="pk_invcl";   
             public static final String  VAPPROVEDATE="vapprovedate";   
             public static final String  VOPERID="voperid";   
             public static final String  VOPERDATE="voperdate";   
             public static final String  INV_NAME="inv_name";   
             public static final String  REMARK="remark";   
             public static final String  INV_NO="inv_no";   
             public static final String  PK_BGINV="pk_bginv";   
      
    
             
             
        public String getPk_corp() {
				return pk_corp;
			}

			public void setPk_corp(String pk_corp) {
				this.pk_corp = pk_corp;
			}

		public String getPk_dept() {
				return pk_dept;
			}

			public void setPk_dept(String pk_dept) {
				this.pk_dept = pk_dept;
			}

		public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public String getOg_invcl() {
				return og_invcl;
			}

			public void setOg_invcl(String og_invcl) {
				this.og_invcl = og_invcl;
			}

			public String getOg_invname() {
				return og_invname;
			}

			public void setOg_invname(String og_invname) {
				this.og_invname = og_invname;
			}

			public String getOg_invno() {
				return og_invno;
			}

			public void setOg_invno(String og_invno) {
				this.og_invno = og_invno;
			}

			public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

		/**
	   * 属性bg_status的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return Integer
	   */
	 public Integer getBg_status() {
		 return bg_status;
	  }   
	  
     /**
	   * 属性bg_status的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newBg_status Integer
	   */
	public void setBg_status(Integer newBg_status) {
		
		bg_status = newBg_status;
	 } 	  
       
        /**
	   * 属性pk_invbasdoc的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getPk_invbasdoc() {
		 return pk_invbasdoc;
	  }   
	  
     /**
	   * 属性pk_invbasdoc的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newPk_invbasdoc String
	   */
	public void setPk_invbasdoc(String newPk_invbasdoc) {
		
		pk_invbasdoc = newPk_invbasdoc;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性pk_invcl的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getPk_invcl() {
		 return pk_invcl;
	  }   
	  
     /**
	   * 属性pk_invcl的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newPk_invcl String
	   */
	public void setPk_invcl(String newPk_invcl) {
		
		pk_invcl = newPk_invcl;
	 } 	  
       
        /**
	   * 属性vapprovedate的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return UFDate
	   */
	 public UFDate getVapprovedate() {
		 return vapprovedate;
	  }   
	  
     /**
	   * 属性vapprovedate的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newVapprovedate UFDate
	   */
	public void setVapprovedate(UFDate newVapprovedate) {
		
		vapprovedate = newVapprovedate;
	 } 	  
       
        /**
	   * 属性voperid的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getVoperid() {
		 return voperid;
	  }   
	  
     /**
	   * 属性voperid的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newVoperid String
	   */
	public void setVoperid(String newVoperid) {
		
		voperid = newVoperid;
	 } 	  
       
        /**
	   * 属性voperdate的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return UFDate
	   */
	 public UFDate getVoperdate() {
		 return voperdate;
	  }   
	  
     /**
	   * 属性voperdate的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newVoperdate UFDate
	   */
	public void setVoperdate(UFDate newVoperdate) {
		
		voperdate = newVoperdate;
	 } 	  
       
        /**
	   * 属性inv_name的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getInv_name() {
		 return inv_name;
	  }   
	  
     /**
	   * 属性inv_name的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newInv_name String
	   */
	public void setInv_name(String newInv_name) {
		
		inv_name = newInv_name;
	 } 	  
       
        /**
	   * 属性remark的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getRemark() {
		 return remark;
	  }   
	  
     /**
	   * 属性remark的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newRemark String
	   */
	public void setRemark(String newRemark) {
		
		remark = newRemark;
	 } 	  
       
        /**
	   * 属性inv_no的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getInv_no() {
		 return inv_no;
	  }   
	  
     /**
	   * 属性inv_no的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newInv_no String
	   */
	public void setInv_no(String newInv_no) {
		
		inv_no = newInv_no;
	 } 	  
       
        /**
	   * 属性pk_bginv的Getter方法.
	   *
	   * 创建日期:2014-4-23
	   * @return String
	   */
	 public String getPk_bginv() {
		 return pk_bginv;
	  }   
	  
     /**
	   * 属性pk_bginv的Setter方法.
	   *
	   * 创建日期:2014-4-23
	   * @param newPk_bginv String
	   */
	public void setPk_bginv(String newPk_bginv) {
		
		pk_bginv = newPk_bginv;
	 } 	  
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-4-23
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-4-23
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_bginv";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-4-23
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_invbasdoc";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-4-23
	  */
	public BgInvEntity() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-4-23
	 * @param newPk_bginv 主键值
	 */
	 public BgInvEntity(String newPk_bginv) {
		
		// 为主键字段赋值:
		 pk_bginv = newPk_bginv;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-4-23
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_bginv;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-4-23
	  * @param newPk_bginv  String    
	  */
	 public void setPrimaryKey(String newPk_bginv) {
				
				pk_bginv = newPk_bginv; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-4-23
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_invbasdoc"; 
				
	 } 
} 
