/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.bxgt.basedoc;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
/**
 * 人员管理档案
 * <p>
 * <strong>提供者：</strong>UAP
 * <p>
 * <strong>使用者：</strong>
 * <p>
 * <strong>设计状态：</strong>详细设计 
 * <p>
 * @version 	UAP5_1.0
 * @author 		chenw
 * @date 2006-10-10
 */
public class PsndocVO extends SuperVO {
	/** serialVersionUID */
	private static final long serialVersionUID = -6827374687307319397L;
	/** 助记码 */
	public String amcode;
	/** 职员编号 */
	public String clerkcode;
	/** 职员标识 */
	public UFBoolean clerkflag;
	/** 自定义项1 */
	public String def1;
	/** 自定义项10 */
	public String def10;
	/** 自定义项11 */
	public String def11;
	/** 自定义项12 */
	public String def12;
	/** 自定义项13 */
	public String def13;
	/** 自定义项14 */
	public String def14;
	/** 自定义项15 */
	public String def15;
	/** 自定义项16 */
	public String def16;
	/** 自定义项17 */
	public String def17;
	/** 自定义项18 */
	public String def18;
	/** 自定义项19 */
	public String def19;
	/** 自定义项2 */
	public String def2;
	/** 自定义项20 */
	public String def20;
	/** 自定义项3 */
	public String def3;
	/** 自定义项4 */
	public String def4;
	/** 自定义项5 */
	public String def5;
	/** 自定义项6 */
	public String def6;
	/** 自定义项7 */
	public String def7;
	/** 自定义项8 */
	public String def8;
	/** 自定义项9 */
	public String def9;
	/** 脏位 
	 * 0 - 正常数据;
	 * 1 - 脏数据;
	 */
	public Integer dr;
	/** 到职日期 */
	
	public String indocflag;
	public UFDate indutydate;
	/** 内部编码 */
	public String innercode;
	/** 岗位等级 */
	public String jobrank;
	/** 岗位序列 */
	public String jobseries;
	/** 下级内部编码最大值 */
	public String maxinnercode;
	/** 离职日期 */
	public UFDate outdutydate;
	/** 公司主键 */
	public String pk_corp;
	/** 所在部门 */
	public String pk_deptdoc;
	/** 岗位主键 */
	public String pk_om_job;
	/** 人员基本档案主键 */
	public String pk_psnbasdoc;
	/** 人员类别 */
	public String pk_psncl;
	/** 人员管理档案主键 */
	public String pk_psndoc;
	/** 归属范围 
	 * 0 - 在职员工;
	 * 2 - 解聘员工;
	 * 3 - 离退员工;
	 * 4 - 调离员工;
	 * 5 - 其他员工;
	 */
	public Integer psnclscope;
	/** 人员编码 */
	public String psncode;
	/** 姓名 */
	public String psnname;
	/** 封存标记 */
	public UFDate sealdate;
	/** 时间戳 */
	public UFDateTime ts;
	

	public PsndocVO() {
		super();
	}
	/**
	 * 使用主键进行初始化的构造子.
	 * @param newPk_psndoc
	 */
	public PsndocVO(String newPk_psndoc) {
		super();
		// 为主键字段赋值:
		pk_psndoc = newPk_psndoc;
	}
	/**
	 * 助记码Getter.
	 * @return
	 */
	public String getAmcode() {
		return amcode;
	}
	/**
	 * 职员编号Getter.
	 * @return
	 */
	public String getClerkcode() {
		return clerkcode;
	}
	/**
	 * 职员标识Getter.
	 * @return
	 */
	public UFBoolean getClerkflag() {
		return clerkflag;
	}
	/**
	 * 自定义项1Getter.
	 * @return
	 */
	public String getDef1() {
		return def1;
	}
	/**
	 * 自定义项10Getter.
	 * @return
	 */
	public String getDef10() {
		return def10;
	}
	/**
	 * 自定义项11Getter.
	 * @return
	 */
	public String getDef11() {
		return def11;
	}
	/**
	 * 自定义项12Getter.
	 * @return
	 */
	public String getDef12() {
		return def12;
	}
	/**
	 * 自定义项13Getter.
	 * @return
	 */
	public String getDef13() {
		return def13;
	}
	/**
	 * 自定义项14Getter.
	 * @return
	 */
	public String getDef14() {
		return def14;
	}
	/**
	 * 自定义项15Getter.
	 * @return
	 */
	public String getDef15() {
		return def15;
	}
	/**
	 * 自定义项16Getter.
	 * @return
	 */
	public String getDef16() {
		return def16;
	}
	/**
	 * 自定义项17Getter.
	 * @return
	 */
	public String getDef17() {
		return def17;
	}
	/**
	 * 自定义项18Getter.
	 * @return
	 */
	public String getDef18() {
		return def18;
	}
	/**
	 * 自定义项19Getter.
	 * @return
	 */
	public String getDef19() {
		return def19;
	}
	/**
	 * 自定义项2Getter.
	 * @return
	 */
	public String getDef2() {
		return def2;
	}
	/**
	 * 自定义项20Getter.
	 * @return
	 */
	public String getDef20() {
		return def20;
	}
	/**
	 * 自定义项3Getter.
	 * @return
	 */
	public String getDef3() {
		return def3;
	}
	/**
	 * 自定义项4Getter.
	 * @return
	 */
	public String getDef4() {
		return def4;
	}
	/**
	 * 自定义项5Getter.
	 * @return
	 */
	public String getDef5() {
		return def5;
	}
	/**
	 * 自定义项6Getter.
	 * @return
	 */
	public String getDef6() {
		return def6;
	}
	/**
	 * 自定义项7Getter.
	 * @return
	 */
	public String getDef7() {
		return def7;
	}
	/**
	 * 自定义项8Getter.
	 * @return
	 */
	public String getDef8() {
		return def8;
	}
	/**
	 * 自定义项9Getter.
	 * @return
	 */
	public String getDef9() {
		return def9;
	}
	/**
	 * 脏位Getter.
	 * @return
	 */
	public Integer getDr() {
		return dr;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#getEntityName()
	 */
	public String getEntityName() {
		return "Psndoc";
	}
	/**
	 * 到职日期Getter.
	 * @return
	 */
	public UFDate getIndutydate() {
		return indutydate;
	}
	/**
	 * 内部编码Getter.
	 * @return
	 */
	public String getInnercode() {
		return innercode;
	}
	/**
	 * 岗位等级Getter.
	 * @return
	 */
	public String getJobrank() {
		return jobrank;
	}
	/**
	 * 岗位等级Getter.
	 * @return
	 */
	public String getJobseries() {
		return jobseries;
	}
	/**
	 * 下级内部编码最大值Getter.
	 * @return
	 */
	public String getMaxinnercode() {
		return maxinnercode;
	}
	/**
	 * 离职日期Getter.
	 * @return
	 */
	public UFDate getOutdutydate() {
		return outdutydate;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#getParentPKFieldName()
	 */
	public java.lang.String getParentPKFieldName() {
		return  null;
	}
	/**
	 * 公司主键Getter.
	 * @return
	 */
	public String getPk_corp() {
		return pk_corp;
	}
	/**
	 * 所在部门Getter.
	 * @return
	 */
	public String getPk_deptdoc() {
		return pk_deptdoc;
	}
	/**
	 * 岗位主键Getter.
	 * @return
	 */
	public String getPk_om_job() {
		return pk_om_job;
	}
	/**
	 * 人员基本档案主键Getter.
	 * @return
	 */
	public String getPk_psnbasdoc() {
		return pk_psnbasdoc;
	}
	/**
	 * 人员基本档案主键Getter.
	 * @return
	 */
	public String getPk_psncl() {
		return pk_psncl;
	}
	/**
	 * 人员管理档案主键Getter.
	 * @return
	 */
	public String getPk_psndoc() {
		return pk_psndoc;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#getPKFieldName()
	 */
	public java.lang.String getPKFieldName() {
		return  "pk_psndoc";
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#getPrimaryKey()
	 */
	public String getPrimaryKey() {
		return pk_psndoc;
	}
	/**
	 * 归属范围Getter.
	 * @return
	 */
	public Integer getPsnclscope() {
		return psnclscope;
	}
	/**
	 * 人员编码Getter.
	 * @return
	 */
	public String getPsncode() {
		return psncode;
	}
	/**
	 * 姓名Getter.
	 * @return
	 */
	public String getPsnname() {
		return psnname;
	}
	/**
	 * 封存标记Getter.
	 * @return
	 */
	public UFDate getSealdate() {
		return sealdate;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#getTableName()
	 */
	public java.lang.String getTableName() {
		return "bd_psndoc";
	}
	/**
	 * 时间戳Getter.
	 * @return
	 */
	public UFDateTime getTs() {
		return ts;
	}
	/**
	 * 助记码Setter.
	 * @param newAmcode
	 */
	public void setAmcode(String newAmcode) {
		amcode = newAmcode;
	}
	/**
	 * 职员编号Setter.
	 * @param newClerkcode
	 */
	public void setClerkcode(String newClerkcode) {
		clerkcode = newClerkcode;
	}
	/**
	 * 职员标识Setter.
	 * @param newClerkflag
	 */
	public void setClerkflag(UFBoolean newClerkflag) {
		clerkflag = newClerkflag;
	}
	/**
	 * 自定义项1Setter.
	 * @param newDef1
	 */
	public void setDef1(String newDef1) {
		def1 = newDef1;
	}
	/**
	 * 自定义项10Setter.
	 * @param newDef10
	 */
	public void setDef10(String newDef10) {
		def10 = newDef10;
	}
	/**
	 * 自定义项11Setter.
	 * @param newDef11
	 */
	public void setDef11(String newDef11) {
		def11 = newDef11;
	}
	/**
	 * 自定义项12Setter.
	 * @param newDef12
	 */
	public void setDef12(String newDef12) {
		def12 = newDef12;
	}
	/**
	 * 自定义项13Setter.
	 * @param newDef13
	 */
	public void setDef13(String newDef13) {
		def13 = newDef13;
	}
	/**
	 * 自定义项14Setter.
	 * @param newDef14
	 */
	public void setDef14(String newDef14) {
		def14 = newDef14;
	}
	/**
	 * 自定义项15Setter.
	 * @param newDef15
	 */
	public void setDef15(String newDef15) {
		def15 = newDef15;
	}
	/**
	 * 自定义项16Setter.
	 * @param newDef16
	 */
	public void setDef16(String newDef16) {
		def16 = newDef16;
	}
	/**
	 * 自定义项17Setter.
	 * @param newDef17
	 */
	public void setDef17(String newDef17) {
		def17 = newDef17;
	}
	/**
	 * 自定义项18Setter.
	 * @param newDef18
	 */
	public void setDef18(String newDef18) {
		def18 = newDef18;
	}
	/**
	 * 自定义项19Setter.
	 * @param newDef19
	 */
	public void setDef19(String newDef19) {
		def19 = newDef19;
	}
	/**
	 * 自定义项2Setter.
	 * @param newDef2
	 */
	public void setDef2(String newDef2) {
		def2 = newDef2;
	}
	/**
	 * 自定义项20Setter.
	 * @param newDef20
	 */
	public void setDef20(String newDef20) {
		def20 = newDef20;
	}
	/**
	 * 自定义项3Setter.
	 * @param newDef3
	 */
	public void setDef3(String newDef3) {
		def3 = newDef3;
	}
	/**
	 * 自定义项4Setter.
	 * @param newDef4
	 */
	public void setDef4(String newDef4) {
		def4 = newDef4;
	}
	/**
	 * 自定义项5Setter.
	 * @param newDef5
	 */
	public void setDef5(String newDef5) {
		def5 = newDef5;
	}
	/**
	 * 自定义项6Setter.
	 * @param newDef6
	 */
	public void setDef6(String newDef6) {
		def6 = newDef6;
	}
	/**
	 * 自定义项7Setter.
	 * @param newDef7
	 */
	public void setDef7(String newDef7) {
		def7 = newDef7;
	}
	/**
	 * 自定义项8Setter.
	 * @param newDef8
	 */
	public void setDef8(String newDef8) {
		def8 = newDef8;
	}
	/**
	 * 自定义项9Setter.
	 * @param newDef9
	 */
	public void setDef9(String newDef9) {
		def9 = newDef9;
	}
	/**
	 * 脏位Setter.
	 * @param newDr
	 */
	public void setDr(Integer newDr) {
		dr = newDr;
	}
	/**
	 * 到职日期Setter.
	 * @param newIndutydate
	 */
	public void setIndutydate(UFDate newIndutydate) {
		indutydate = newIndutydate;
	}
	/**
	 * 内部编码Setter.
	 * @param newInnercode
	 */
	public void setInnercode(String newInnercode) {
		innercode = newInnercode;
	}
	/**
	 * 岗位等级Setter.
	 * @param newJobrank
	 */
	public void setJobrank(String newJobrank) {
		jobrank = newJobrank;
	}
	/**
	 * 岗位序列Setter.
	 * @param newJobseries
	 */
	public void setJobseries(String newJobseries) {
		jobseries = newJobseries;
	}
	/**
	 * 下级内部编码最大值Setter.
	 * @param newMaxinnercode
	 */
	public void setMaxinnercode(String newMaxinnercode) {
		maxinnercode = newMaxinnercode;
	}
	/**
	 * 离职日期Setter.
	 * @param newOutdutydate
	 */
	public void setOutdutydate(UFDate newOutdutydate) {
		outdutydate = newOutdutydate;
	}
	/**
	 * 公司主键Setter.
	 * @param newPk_corp
	 */
	public void setPk_corp(String newPk_corp) {
		pk_corp = newPk_corp;
	}
	/**
	 * 所在部门Setter.
	 * @param newPk_deptdoc
	 */
	public void setPk_deptdoc(String newPk_deptdoc) {
		pk_deptdoc = newPk_deptdoc;
	}
	/**
	 * 岗位主键Setter.
	 * @param newPk_om_job
	 */
	public void setPk_om_job(String newPk_om_job) {
		pk_om_job = newPk_om_job;
	}
	/**
	 * 人员基本档案主键Setter.
	 * @param newPk_psnbasdoc
	 */
	public void setPk_psnbasdoc(String newPk_psnbasdoc) {
		pk_psnbasdoc = newPk_psnbasdoc;
	}
	/**
	 * 人员类别Setter.
	 * @param newPk_psncl
	 */
	public void setPk_psncl(String newPk_psncl) {
		pk_psncl = newPk_psncl;
	}
	/**
	 * 人员管理档案主键Setter.
	 * @param pk_psndoc
	 */
	public void setPk_psndoc(String pk_psndoc) {
		this.pk_psndoc = pk_psndoc;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#setPrimaryKey(java.lang.String)
	 */
	public void setPrimaryKey(String newPk_psndoc) {
		pk_psndoc = newPk_psndoc;
	}
	/**
	 * 归属范围Setter.
	 * @param newPsnclscope
	 */
	public void setPsnclscope(Integer newPsnclscope) {
		psnclscope = newPsnclscope;
	}
	/**
	 * 人员编码Setter.
	 * @param newPsncode
	 */
	public void setPsncode(String newPsncode) {
		psncode = newPsncode;
	}
	/**
	 * 姓名Setter.
	 * @param newPsnname
	 */
	public void setPsnname(String newPsnname) {
		psnname = newPsnname;
	}
	/**
	 * 封存标记Setter.
	 * @param newSealdate
	 */
	public void setSealdate(UFDate newSealdate) {
		sealdate = newSealdate;
	}
	/**
	 * 时间戳Setter.
	 * @param newTs
	 */
	public void setTs(UFDateTime newTs) {
		ts = newTs;
	}
	/* (non-Javadoc)
	 * @see nc.vo.pub.SuperVO#validate()
	 */
	public void validate() throws ValidationException {
		ArrayList<String> errFields = new ArrayList<String>(); // errFields record those null fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
		if (pk_psnbasdoc == null) {
			errFields.add(new String("pk_psnbasdoc"));
		}
		if (pk_psncl == null) {
			errFields.add(new String("pk_psncl"));
		}
		if (pk_psndoc == null) {
			errFields.add(new String("pk_psndoc"));
		}
		if (psncode == null) {
			errFields.add(new String("psncode"));
		}
		// construct the exception message:
		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("10080604","UPP10080604-000011")/*@res "下列字段不能为空:"*/);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for ( int i= 1; i < temp.length; i++ ) {
				message.append(",");
				message.append(temp[i]);
			}
			// throw the exception:
			throw new NullFieldException(message.toString());
		}
	}
	public String getIndocflag() {
		return indocflag;
	}
	public void setIndocflag(String indocflag) {
		this.indocflag = indocflag;
	}
}