  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkjh;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-31
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkjhprintVO extends SuperVO {
       
    	 public String pk_fkjhprint;
    	 public String corp_name;
    	 public UFDate print_date;
    	 public String dept_name;
    	 public String dept_saleman;
    	 public String dept_master;
    	 public String say_corp;
    	 public String say_bank;
    	 public String say_no;
    	 public String say_content;
    	 public String say_type;
    	 public UFDouble amount_sum;
    	 public String htcode1;
    	 public UFDouble htamount1;
    	 public String say_content1;
    	 public String say_type1;
    	 public String htcode2;
    	 public UFDouble htamount2;
    	 public String say_content2;
    	 public String say_type2;
    	 public String htcode3;
    	 public UFDouble htamount3;
    	 public String say_content3;
    	 public String say_type3;
    	 public String htcode4;
    	 public UFDouble htamount4;
    	 public String say_content4;
    	 public String say_type4;
    	 public String htcode5;
    	 public UFDouble htamount5;
    	 public String say_content5;
    	 public String say_type5;
    	 public String htcode6;
    	 public UFDouble htamount6;
    	 public String say_content6;
    	 public String say_type6;
    	 public String htcode7;
    	 public UFDouble htamount7;
    	 public String say_content7;
    	 public String say_type7;
    	 public String htcode8;
    	 public UFDouble htamount8;
    	 public String say_content8;
    	 public String say_type8;
    	 public String htcode9;
    	 public UFDouble htamount9;
    	 public String say_content9;
    	 public String say_type9;
    	 public String htcode10;
    	 public UFDouble htamount10;
    	 public String say_content10;
    	 public String say_type10;
    	 public String htcode11;
    	 public UFDouble htamount11;
    	 public String htcode12;
    	 public UFDouble htamount12;
    	 public String htcode13;
    	 public UFDouble htamount13;
    	 public String htcode14;
    	 public UFDouble htamount14;
    	 public Integer dr;
    	 public UFDateTime ts;
    	 public String print_no;
    	 public String fzname;
    	 
    	 public String cwname;
    	 
    	 
    	 
   	public String getCwname() {
			return cwname;
		}

		public void setCwname(String cwname) {
			this.cwname = cwname;
		}

	public String getSay_content1() {
			return say_content1;
		}

		public void setSay_content1(String say_content1) {
			this.say_content1 = say_content1;
		}

		public String getSay_content10() {
			return say_content10;
		}

		public void setSay_content10(String say_content10) {
			this.say_content10 = say_content10;
		}

		public String getSay_content2() {
			return say_content2;
		}

		public void setSay_content2(String say_content2) {
			this.say_content2 = say_content2;
		}

		public String getSay_content3() {
			return say_content3;
		}

		public void setSay_content3(String say_content3) {
			this.say_content3 = say_content3;
		}

		public String getSay_content4() {
			return say_content4;
		}

		public void setSay_content4(String say_content4) {
			this.say_content4 = say_content4;
		}

		public String getSay_content5() {
			return say_content5;
		}

		public void setSay_content5(String say_content5) {
			this.say_content5 = say_content5;
		}

		public String getSay_content6() {
			return say_content6;
		}

		public void setSay_content6(String say_content6) {
			this.say_content6 = say_content6;
		}

		public String getSay_content7() {
			return say_content7;
		}

		public void setSay_content7(String say_content7) {
			this.say_content7 = say_content7;
		}

		public String getSay_content8() {
			return say_content8;
		}

		public void setSay_content8(String say_content8) {
			this.say_content8 = say_content8;
		}

		public String getSay_content9() {
			return say_content9;
		}

		public void setSay_content9(String say_content9) {
			this.say_content9 = say_content9;
		}

		public String getSay_type1() {
			return say_type1;
		}

		public void setSay_type1(String say_type1) {
			this.say_type1 = say_type1;
		}

		public String getSay_type10() {
			return say_type10;
		}

		public void setSay_type10(String say_type10) {
			this.say_type10 = say_type10;
		}

		public String getSay_type2() {
			return say_type2;
		}

		public void setSay_type2(String say_type2) {
			this.say_type2 = say_type2;
		}

		public String getSay_type3() {
			return say_type3;
		}

		public void setSay_type3(String say_type3) {
			this.say_type3 = say_type3;
		}

		public String getSay_type4() {
			return say_type4;
		}

		public void setSay_type4(String say_type4) {
			this.say_type4 = say_type4;
		}

		public String getSay_type5() {
			return say_type5;
		}

		public void setSay_type5(String say_type5) {
			this.say_type5 = say_type5;
		}

		public String getSay_type6() {
			return say_type6;
		}

		public void setSay_type6(String say_type6) {
			this.say_type6 = say_type6;
		}

		public String getSay_type7() {
			return say_type7;
		}

		public void setSay_type7(String say_type7) {
			this.say_type7 = say_type7;
		}

		public String getSay_type8() {
			return say_type8;
		}

		public void setSay_type8(String say_type8) {
			this.say_type8 = say_type8;
		}

		public String getSay_type9() {
			return say_type9;
		}

		public void setSay_type9(String say_type9) {
			this.say_type9 = say_type9;
		}

	public String getFzname() {
			return fzname;
		}

		public void setFzname(String fzname) {
			this.fzname = fzname;
		}

	public String getPrint_no() {
			return print_no;
		}

		public void setPrint_no(String print_no) {
			this.print_no = print_no;
		}

	public UFDouble getAmount_sum() {
			return amount_sum;
		}

		public void setAmount_sum(UFDouble amount_sum) {
			this.amount_sum = amount_sum;
		}

		public String getCorp_name() {
			return corp_name;
		}

		public void setCorp_name(String corp_name) {
			this.corp_name = corp_name;
		}

		public String getDept_master() {
			return dept_master;
		}

		public void setDept_master(String dept_master) {
			this.dept_master = dept_master;
		}

		public String getDept_name() {
			return dept_name;
		}

		public void setDept_name(String dept_name) {
			this.dept_name = dept_name;
		}

		public String getDept_saleman() {
			return dept_saleman;
		}

		public void setDept_saleman(String dept_saleman) {
			this.dept_saleman = dept_saleman;
		}

		public Integer getDr() {
			return dr;
		}

		public void setDr(Integer dr) {
			this.dr = dr;
		}

		public UFDouble getHtamount1() {
			return htamount1;
		}

		public void setHtamount1(UFDouble htamount1) {
			this.htamount1 = htamount1;
		}

		public UFDouble getHtamount10() {
			return htamount10;
		}

		public void setHtamount10(UFDouble htamount10) {
			this.htamount10 = htamount10;
		}

		public UFDouble getHtamount11() {
			return htamount11;
		}

		public void setHtamount11(UFDouble htamount11) {
			this.htamount11 = htamount11;
		}

		public UFDouble getHtamount12() {
			return htamount12;
		}

		public void setHtamount12(UFDouble htamount12) {
			this.htamount12 = htamount12;
		}

		public UFDouble getHtamount13() {
			return htamount13;
		}

		public void setHtamount13(UFDouble htamount13) {
			this.htamount13 = htamount13;
		}

		public UFDouble getHtamount14() {
			return htamount14;
		}

		public void setHtamount14(UFDouble htamount14) {
			this.htamount14 = htamount14;
		}

		public UFDouble getHtamount2() {
			return htamount2;
		}

		public void setHtamount2(UFDouble htamount2) {
			this.htamount2 = htamount2;
		}

		public UFDouble getHtamount3() {
			return htamount3;
		}

		public void setHtamount3(UFDouble htamount3) {
			this.htamount3 = htamount3;
		}

		public UFDouble getHtamount4() {
			return htamount4;
		}

		public void setHtamount4(UFDouble htamount4) {
			this.htamount4 = htamount4;
		}

		public UFDouble getHtamount5() {
			return htamount5;
		}

		public void setHtamount5(UFDouble htamount5) {
			this.htamount5 = htamount5;
		}

		public UFDouble getHtamount6() {
			return htamount6;
		}

		public void setHtamount6(UFDouble htamount6) {
			this.htamount6 = htamount6;
		}

		public UFDouble getHtamount7() {
			return htamount7;
		}

		public void setHtamount7(UFDouble htamount7) {
			this.htamount7 = htamount7;
		}

		public UFDouble getHtamount8() {
			return htamount8;
		}

		public void setHtamount8(UFDouble htamount8) {
			this.htamount8 = htamount8;
		}

		public UFDouble getHtamount9() {
			return htamount9;
		}

		public void setHtamount9(UFDouble htamount9) {
			this.htamount9 = htamount9;
		}

		public String getHtcode1() {
			return htcode1;
		}

		public void setHtcode1(String htcode1) {
			this.htcode1 = htcode1;
		}

		public String getHtcode10() {
			return htcode10;
		}

		public void setHtcode10(String htcode10) {
			this.htcode10 = htcode10;
		}

		public String getHtcode11() {
			return htcode11;
		}

		public void setHtcode11(String htcode11) {
			this.htcode11 = htcode11;
		}

		public String getHtcode12() {
			return htcode12;
		}

		public void setHtcode12(String htcode12) {
			this.htcode12 = htcode12;
		}

		public String getHtcode13() {
			return htcode13;
		}

		public void setHtcode13(String htcode13) {
			this.htcode13 = htcode13;
		}

		public String getHtcode14() {
			return htcode14;
		}

		public void setHtcode14(String htcode14) {
			this.htcode14 = htcode14;
		}

		public String getHtcode2() {
			return htcode2;
		}

		public void setHtcode2(String htcode2) {
			this.htcode2 = htcode2;
		}

		public String getHtcode3() {
			return htcode3;
		}

		public void setHtcode3(String htcode3) {
			this.htcode3 = htcode3;
		}

		public String getHtcode4() {
			return htcode4;
		}

		public void setHtcode4(String htcode4) {
			this.htcode4 = htcode4;
		}

		public String getHtcode5() {
			return htcode5;
		}

		public void setHtcode5(String htcode5) {
			this.htcode5 = htcode5;
		}

		public String getHtcode6() {
			return htcode6;
		}

		public void setHtcode6(String htcode6) {
			this.htcode6 = htcode6;
		}

		public String getHtcode7() {
			return htcode7;
		}

		public void setHtcode7(String htcode7) {
			this.htcode7 = htcode7;
		}

		public String getHtcode8() {
			return htcode8;
		}

		public void setHtcode8(String htcode8) {
			this.htcode8 = htcode8;
		}

		public String getHtcode9() {
			return htcode9;
		}

		public void setHtcode9(String htcode9) {
			this.htcode9 = htcode9;
		}

		public String getPk_fkjhprint() {
			return pk_fkjhprint;
		}

		public void setPk_fkjhprint(String pk_fkjhprint) {
			this.pk_fkjhprint = pk_fkjhprint;
		}

		public UFDate getPrint_date() {
			return print_date;
		}

		public void setPrint_date(UFDate print_date) {
			this.print_date = print_date;
		}

		public String getSay_bank() {
			return say_bank;
		}

		public void setSay_bank(String say_bank) {
			this.say_bank = say_bank;
		}

		public String getSay_content() {
			return say_content;
		}

		public void setSay_content(String say_content) {
			this.say_content = say_content;
		}

		public String getSay_corp() {
			return say_corp;
		}

		public void setSay_corp(String say_corp) {
			this.say_corp = say_corp;
		}

		public String getSay_no() {
			return say_no;
		}

		public void setSay_no(String say_no) {
			this.say_no = say_no;
		}

		public String getSay_type() {
			return say_type;
		}

		public void setSay_type(String say_type) {
			this.say_type = say_type;
		}

		public UFDateTime getTs() {
			return ts;
		}

		public void setTs(UFDateTime ts) {
			this.ts = ts;
		}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkjhprint";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkjhprint";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-31
	  */
	public DhFkjhprintVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-31
	 * @param newPk_fkjhbill 主键值
	 */
	 public DhFkjhprintVO(String newPk_fkjhbill) {
		
		// 为主键字段赋值:
		 pk_fkjhprint = newPk_fkjhbill;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-31
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkjhprint;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-31
	  * @param newPk_fkjhbill  String    
	  */
	 public void setPrimaryKey(String newPk_fkjhbill) {
				
		 pk_fkjhprint = newPk_fkjhbill; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-31
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkjhprint"; 
				
	 }

} 
