  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.jcInfo.custInfo;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-4-23
 * @author author
 * @version Your Project 1.0
 */
     public class BgCustEntity extends SuperVO {
           
    	 public String pk_bgcust;
    	 public Integer cust_flag;
    	 public Integer cust_status;
    	 public String pk_cubasdoc;
    	 public String og_custno;
    	 public String og_custname;
    	 public String cust_no;
    	 public String cust_name;
    	 public String vemo;
    	 public String voerid;
    	 public String vapproveid;
    	 public String pk_dept;
    	 public String pk_corp;
    	 public UFDate voperdate;
    	 public UFDate vapprovedate;
    	 public Integer dr;
    	 public UFDateTime ts;
       
    	 public static final String PK_BGCUST="pk_bgcust";
    	 public static final String CUST_FLAG="cust_flag";
    	 public static final String CUST_STATUS="cust_status";
    	 public static final String PK_CUBASDOC="pk_cubasdoc";
    	 public static final String OG_CUSTNO="og_custno";
    	 public static final String OG_CUSTNAME="og_custname";
    	 public static final String CUST_NO="cust_no";
    	 public static final String CUST_NAME="cust_name";
    	 public static final String VEMO="vemo";
    	 public static final String VOERID="voerid";
    	 public static final String VAPPROVEID="vapproveid";
    	 public static final String PK_DEPT="pk_dept";
    	 public static final String PK_CORP="pk_corp";
    	 public static final String VOPERDATE="voperdate";
    	 public static final String VAPPROVEDATE="vapprovedate";
    	 public static final String DR="dr";
    	 public static final String TS="ts"; 
    	 
    	 
    	 public Integer getCust_flag() {
			return cust_flag;
		}

		public void setCust_flag(Integer cust_flag) {
			this.cust_flag = cust_flag;
		}

		public String getCust_name() {
			return cust_name;
		}

		public void setCust_name(String cust_name) {
			this.cust_name = cust_name;
		}

		public String getCust_no() {
			return cust_no;
		}

		public void setCust_no(String cust_no) {
			this.cust_no = cust_no;
		}

		public Integer getCust_status() {
			return cust_status;
		}

		public void setCust_status(Integer cust_status) {
			this.cust_status = cust_status;
		}

		public Integer getDr() {
			return dr;
		}

		public void setDr(Integer dr) {
			this.dr = dr;
		}

		public String getOg_custname() {
			return og_custname;
		}

		public void setOg_custname(String og_custname) {
			this.og_custname = og_custname;
		}

		public String getOg_custno() {
			return og_custno;
		}

		public void setOg_custno(String og_custno) {
			this.og_custno = og_custno;
		}

		public String getPk_bgcust() {
			return pk_bgcust;
		}

		public void setPk_bgcust(String pk_bgcust) {
			this.pk_bgcust = pk_bgcust;
		}

		public String getPk_corp() {
			return pk_corp;
		}

		public void setPk_corp(String pk_corp) {
			this.pk_corp = pk_corp;
		}

		public String getPk_cubasdoc() {
			return pk_cubasdoc;
		}

		public void setPk_cubasdoc(String pk_cubasdoc) {
			this.pk_cubasdoc = pk_cubasdoc;
		}

		public String getPk_dept() {
			return pk_dept;
		}

		public void setPk_dept(String pk_dept) {
			this.pk_dept = pk_dept;
		}

		public UFDateTime getTs() {
			return ts;
		}

		public void setTs(UFDateTime ts) {
			this.ts = ts;
		}

		public UFDate getVapprovedate() {
			return vapprovedate;
		}

		public void setVapprovedate(UFDate vapprovedate) {
			this.vapprovedate = vapprovedate;
		}

		public String getVapproveid() {
			return vapproveid;
		}

		public void setVapproveid(String vapproveid) {
			this.vapproveid = vapproveid;
		}

		public String getVemo() {
			return vemo;
		}

		public void setVemo(String vemo) {
			this.vemo = vemo;
		}

		public String getVoerid() {
			return voerid;
		}

		public void setVoerid(String voerid) {
			this.voerid = voerid;
		}

		public UFDate getVoperdate() {
			return voperdate;
		}

		public void setVoperdate(UFDate voperdate) {
			this.voperdate = voperdate;
		}

	public java.lang.String getParentPKFieldName() {
		return null;
	}   
    
	public java.lang.String getPKFieldName() {
		return "pk_bgcust";
	}
    
	public java.lang.String getTableName() {
		return "dh_cubasdoc";
	}    
    
	public BgCustEntity() {
		super();	
	}    
    
	public BgCustEntity(String newPk_bgcust) {
		pk_bgcust = newPk_bgcust;
   	}

	public String getPrimaryKey() {
		return pk_bgcust;
	}

	public void setPrimaryKey(String newPk_bgcust) {
		pk_bgcust = newPk_bgcust; 
	} 

	public String getEntityName() {
	   return "dh_cubasdoc"; 
	} 
} 
