  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.htinfo.htquery;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-4-2
 * @author author
 * @version Your Project 1.0
 */
     public class HtConLogoEntity extends SuperVO {
    	 
             public UFDate htdeldate;
             public String corp_manager;
             public String dept_contractor;
             public String htstyle;
             public String jobcode;
             public String belong_dept;
             public String httype;
             public String adding_dept;
             public String dept_manager;
             public String custname;
             public String bank_name;
             public String sax_no;
             public UFDate htdate;
             public UFDate voperdate;
             public String htmanager;
             public String vemo;
             public String cttype;
             public String htdeladdress;
             public String pk_conlogo;
             public String voperator;
             public String corp_name;
             public String jobname;
             public String htname;
             public String htcontractor;
             public String htaddress;
             public String htcode;
             public UFDate htexedate;
             public UFDouble htamount;
             public UFDouble xmaccount;
             
             public String pk_contract;
             public String pk_deptmanager;
             public String pk_cust;
             public String pk_htname;
             public String pk_corp;
             
             public static final String  HTDELDATE="htdeldate";   
             public static final String  CORP_MANAGER="corp_manager";   
             public static final String  DEPT_CONTRACTOR="dept_contractor";   
             public static final String  HTSTYLE="htstyle";   
             public static final String  JOBCODE="jobcode";   
             public static final String  BELONG_DEPT="belong_dept";   
             public static final String  HTTYPE="httype";   
             public static final String  ADDING_DEPT="adding_dept";   
             public static final String  DEPT_MANAGER="dept_manager";   
             public static final String  CUSTNAME="custname";   
             public static final String  BANK_NAME="bank_name";   
             public static final String  SAX_NO="sax_no";   
             public static final String  HTDATE="htdate";   
             public static final String  VOPERDATE="voperdate";   
             public static final String  HTMANAGER="htmanager";   
             public static final String  VEMO="vemo";   
             public static final String  CTTYPE="cttype";   
             public static final String  HTDELADDRESS="htdeladdress";   
             public static final String  PK_CONLOGO="pk_conlogo";   
             public static final String  VOPERATOR="voperator";   
             public static final String  CORP_NAME="corp_name";   
             public static final String  JOBNAME="jobname";   
             public static final String  HTNAME="htname";   
             public static final String  HTCONTRACTOR="htcontractor";   
             public static final String  HTADDRESS="htaddress";   
             public static final String  HTCODE="htcode";   
             public static final String  HTEXEDATE="htexedate";   
             public static final String  HTAMOUNT="htamount";   
             public static final String  XMACCOUNT = "xmaccount";
    	 
             
             
        public String getPk_corp() {
				return pk_corp;
			}

			public void setPk_corp(String pk_corp) {
				this.pk_corp = pk_corp;
			}

		public String getPk_contract() {
				return pk_contract;
			}

			public void setPk_contract(String pk_contract) {
				this.pk_contract = pk_contract;
			}

			public String getPk_cust() {
				return pk_cust;
			}

			public void setPk_cust(String pk_cust) {
				this.pk_cust = pk_cust;
			}

			public String getPk_deptmanager() {
				return pk_deptmanager;
			}

			public void setPk_deptmanager(String pk_deptmanager) {
				this.pk_deptmanager = pk_deptmanager;
			}

			public String getPk_htname() {
				return pk_htname;
			}

			public void setPk_htname(String pk_htname) {
				this.pk_htname = pk_htname;
			}

		/**
	   * 属性htdeldate的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return UFDate
	   */
	 public UFDate getHtdeldate() {
		 return htdeldate;
		}

     /**
	   * 属性htdeldate的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtdeldate UFDate
	   */
	public void setHtdeldate(UFDate newHtdeldate) {

		htdeldate = newHtdeldate;
		}

        /**
	   * 属性corp_manager的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getCorp_manager() {
		 return corp_manager;
		}

     /**
	   * 属性corp_manager的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newCorp_manager String
	   */
	public void setCorp_manager(String newCorp_manager) {

		corp_manager = newCorp_manager;
		}

        /**
	   * 属性dept_contractor的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getDept_contractor() {
		 return dept_contractor;
		}

     /**
	   * 属性dept_contractor的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newDept_contractor String
	   */
	public void setDept_contractor(String newDept_contractor) {

		dept_contractor = newDept_contractor;
		}

        /**
	   * 属性htstyle的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtstyle() {
		 return htstyle;
		}

     /**
	   * 属性htstyle的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtstyle String
	   */
	public void setHtstyle(String newHtstyle) {

		htstyle = newHtstyle;
		}

        /**
	   * 属性jobcode的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getJobcode() {
		 return jobcode;
		}

     /**
	   * 属性jobcode的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newJobcode String
	   */
	public void setJobcode(String newJobcode) {

		jobcode = newJobcode;
		}

        /**
	   * 属性belong_dept的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getBelong_dept() {
		 return belong_dept;
		}

     /**
	   * 属性belong_dept的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newBelong_dept String
	   */
	public void setBelong_dept(String newBelong_dept) {

		belong_dept = newBelong_dept;
		}

        /**
	   * 属性httype的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHttype() {
		 return httype;
		}

     /**
	   * 属性httype的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHttype String
	   */
	public void setHttype(String newHttype) {

		httype = newHttype;
		}

        /**
	   * 属性adding_dept的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getAdding_dept() {
		 return adding_dept;
		}

     /**
	   * 属性adding_dept的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newAdding_dept String
	   */
	public void setAdding_dept(String newAdding_dept) {

		adding_dept = newAdding_dept;
		}

        /**
	   * 属性dept_manager的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
		public String getDept_manager() {
			return dept_manager;
		}

     /**
	   * 属性dept_manager的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newDept_manager String
	   */
	public void setDept_manager(String newDept_manager) {

		dept_manager = newDept_manager;
		}

        /**
	   * 属性custname的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getCustname() {
		 return custname;
		}

     /**
	   * 属性custname的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newCustname String
	   */
	public void setCustname(String newCustname) {

		custname = newCustname;
		}

        /**
	   * 属性bank_name的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getBank_name() {
		 return bank_name;
		}

     /**
	   * 属性bank_name的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newBank_name String
	   */
	public void setBank_name(String newBank_name) {

		bank_name = newBank_name;
		}

        /**
	   * 属性sax_no的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getSax_no() {
		 return sax_no;
		}

     /**
	   * 属性sax_no的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newSax_no String
	   */
	public void setSax_no(String newSax_no) {

		sax_no = newSax_no;
		}

        /**
	   * 属性htdate的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return UFDate
	   */
		public UFDate getHtdate() {
			return htdate;
		}

     /**
	   * 属性htdate的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtdate UFDate
	   */
	public void setHtdate(UFDate newHtdate) {

		htdate = newHtdate;
		}

        /**
	   * 属性voperdate的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return UFDate
	   */
	 public UFDate getVoperdate() {
		 return voperdate;
		}

     /**
	   * 属性voperdate的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newVoperdate UFDate
	   */
	public void setVoperdate(UFDate newVoperdate) {

		voperdate = newVoperdate;
		}

        /**
	   * 属性htmanager的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtmanager() {
		 return htmanager;
		}

     /**
	   * 属性htmanager的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtmanager String
	   */
	public void setHtmanager(String newHtmanager) {

		htmanager = newHtmanager;
		}

        /**
	   * 属性vemo的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getVemo() {
		 return vemo;
		}

     /**
	   * 属性vemo的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newVemo String
	   */
	public void setVemo(String newVemo) {

		vemo = newVemo;
		}

        /**
	   * 属性cttype的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getCttype() {
		 return cttype;
		}

     /**
	   * 属性cttype的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newCttype String
	   */
	public void setCttype(String newCttype) {

		cttype = newCttype;
		}

        /**
	   * 属性htdeladdress的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtdeladdress() {
		 return htdeladdress;
		}

     /**
	   * 属性htdeladdress的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtdeladdress String
	   */
	public void setHtdeladdress(String newHtdeladdress) {

		htdeladdress = newHtdeladdress;
		}

        /**
	   * 属性pk_conlogo的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getPk_conlogo() {
		 return pk_conlogo;
		}

     /**
	   * 属性pk_conlogo的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newPk_conlogo String
	   */
	public void setPk_conlogo(String newPk_conlogo) {

		pk_conlogo = newPk_conlogo;
		}

        /**
	   * 属性voperator的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getVoperator() {
		 return voperator;
		}

     /**
	   * 属性voperator的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newVoperator String
	   */
	public void setVoperator(String newVoperator) {

		voperator = newVoperator;
		}

        /**
	   * 属性corp_name的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getCorp_name() {
		 return corp_name;
		}

     /**
	   * 属性corp_name的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newCorp_name String
	   */
	public void setCorp_name(String newCorp_name) {

		corp_name = newCorp_name;
		}

        /**
	   * 属性jobname的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
		public String getJobname() {
			return jobname;
		}

     /**
	   * 属性jobname的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newJobname String
	   */
	public void setJobname(String newJobname) {

		jobname = newJobname;
		}

        /**
	   * 属性htname的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtname() {
		 return htname;
		}

     /**
	   * 属性htname的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtname String
	   */
	public void setHtname(String newHtname) {

		htname = newHtname;
		}

        /**
	   * 属性htcontractor的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtcontractor() {
		 return htcontractor;
		}

     /**
	   * 属性htcontractor的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtcontractor String
	   */
	public void setHtcontractor(String newHtcontractor) {

		htcontractor = newHtcontractor;
		}

        /**
	   * 属性htaddress的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtaddress() {
		 return htaddress;
		}

     /**
	   * 属性htaddress的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtaddress String
	   */
	public void setHtaddress(String newHtaddress) {

		htaddress = newHtaddress;
		}

        /**
	   * 属性htcode的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return String
	   */
	 public String getHtcode() {
		 return htcode;
		}

     /**
	   * 属性htcode的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtcode String
	   */
	public void setHtcode(String newHtcode) {

		htcode = newHtcode;
		}

        /**
	   * 属性htexedate的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return UFDate
	   */
	 public UFDate getHtexedate() {
		 return htexedate;
		}

     /**
	   * 属性htexedate的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtexedate UFDate
	   */
	public void setHtexedate(UFDate newHtexedate) {

		htexedate = newHtexedate;
		}

        /**
	   * 属性htamount的Getter方法.
	   *
	   * 创建日期:2014-4-2
	   * @return UFDouble
	   */
	 public UFDouble getHtamount() {
		 return htamount;
		}

     /**
	   * 属性htamount的Setter方法.
	   *
	   * 创建日期:2014-4-2
	   * @param newHtamount UFDouble
	   */
	public void setHtamount(UFDouble newHtamount) {

		htamount = newHtamount;
		}


	/**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-4-2
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_conlogo == null) {
			errFields.add(new String("pk_conlogo"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_conlogo";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-4-2
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_conlogo";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-4-2
	  */
	public HtConLogoEntity() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-4-2
	 * @param newPk_conlogo 主键值
	 */
	 public HtConLogoEntity(String newPk_conlogo) {
		
		// 为主键字段赋值:
		 pk_conlogo = newPk_conlogo;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_conlogo;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-4-2
	  * @param newPk_conlogo  String    
	  */
	 public void setPrimaryKey(String newPk_conlogo) {
				
		 pk_conlogo = newPk_conlogo; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-4-2
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_conlogo"; 
				
	 }

	public UFDouble getXmaccount() {
		return xmaccount;
	}

	public void setXmaccount(UFDouble xmaccount) {
		this.xmaccount = xmaccount;
	} 
	 
} 
