  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.ivInfo;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-7-7
 * @author author
 * @version Your Project 1.0
 */
     public class PdutVO extends SuperVO {
           
             public String pdu_name;
             public UFDate suredate;
             public UFDate vappdate;
             public String pdu_type;
             public String fuzongid;
             public String pk_dhpdu;
             public String pk_dnaw;
             public String voperid;
             public UFDate voperdate;
             public String pdu_no;
             public String vemo;
             public Integer dhpdu_flag;
             public String caiwuid;
             public UFDateTime ts;
             public Integer dr=0;
             public String gcbid;
             public UFDate gcbdate;
             public String ret_vemo;
             public Integer dj_status;
             
             public String pkivmandoc;
             public String pk_corp;
            
             public static final String  PDU_NAME="pdu_name";   
             public static final String  SUREDATE="suredate";   
             public static final String  VAPPDATE="vappdate";   
             public static final String  PDU_TYPE="pdu_type";   
             public static final String  FUZONGID="fuzongid";   
             public static final String  PK_DHPDU="pk_dhpdu";   
             public static final String  PK_DNAW="pk_dnaw";   
             public static final String  VOPERID="voperid";   
             public static final String  VOPERDATE="voperdate";   
             public static final String  PDU_NO="pdu_no";   
             public static final String  VEMO="vemo";   
             public static final String  DHPDU_FLAG="dhpdu_flag";   
             public static final String  CAIWUID="caiwuid";   
      
             
             
    
        public String getPk_corp() {
				return pk_corp;
			}

			public void setPk_corp(String pk_corp) {
				this.pk_corp = pk_corp;
			}

		public String getPkivmandoc() {
				return pkivmandoc;
			}

			public void setPkivmandoc(String pkivmandoc) {
				this.pkivmandoc = pkivmandoc;
			}

		public Integer getDj_status() {
				return dj_status;
			}

			public void setDj_status(Integer dj_status) {
				this.dj_status = dj_status;
			}

		public UFDate getGcbdate() {
				return gcbdate;
			}

			public void setGcbdate(UFDate gcbdate) {
				this.gcbdate = gcbdate;
			}

			public String getGcbid() {
				return gcbid;
			}

			public void setGcbid(String gcbid) {
				this.gcbid = gcbid;
			}

			public String getRet_vemo() {
				return ret_vemo;
			}

			public void setRet_vemo(String ret_vemo) {
				this.ret_vemo = ret_vemo;
			}

		public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

		/**
	   * 属性pdu_name的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getPdu_name() {
		 return pdu_name;
	  }   
	  
     /**
	   * 属性pdu_name的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newPdu_name String
	   */
	public void setPdu_name(String newPdu_name) {
		
		pdu_name = newPdu_name;
	 } 	  
       
        /**
	   * 属性suredate的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return UFDate
	   */
	 public UFDate getSuredate() {
		 return suredate;
	  }   
	  
     /**
	   * 属性suredate的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newSuredate UFDate
	   */
	public void setSuredate(UFDate newSuredate) {
		
		suredate = newSuredate;
	 } 	  
       
        /**
	   * 属性vappdate的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return UFDate
	   */
	 public UFDate getVappdate() {
		 return vappdate;
	  }   
	  
     /**
	   * 属性vappdate的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newVappdate UFDate
	   */
	public void setVappdate(UFDate newVappdate) {
		
		vappdate = newVappdate;
	 } 	  
       
        /**
	   * 属性pdu_type的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getPdu_type() {
		 return pdu_type;
	  }   
	  
     /**
	   * 属性pdu_type的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newPdu_type String
	   */
	public void setPdu_type(String newPdu_type) {
		
		pdu_type = newPdu_type;
	 } 	  
       
        /**
	   * 属性fuzongid的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getFuzongid() {
		 return fuzongid;
	  }   
	  
     /**
	   * 属性fuzongid的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newFuzongid String
	   */
	public void setFuzongid(String newFuzongid) {
		
		fuzongid = newFuzongid;
	 } 	  
       
        /**
	   * 属性pk_dhpdu的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getPk_dhpdu() {
		 return pk_dhpdu;
	  }   
	  
     /**
	   * 属性pk_dhpdu的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newPk_dhpdu String
	   */
	public void setPk_dhpdu(String newPk_dhpdu) {
		
		pk_dhpdu = newPk_dhpdu;
	 } 	  
       
        /**
	   * 属性pk_dnaw的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getPk_dnaw() {
		 return pk_dnaw;
	  }   
	  
     /**
	   * 属性pk_dnaw的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newPk_dnaw String
	   */
	public void setPk_dnaw(String newPk_dnaw) {
		
		pk_dnaw = newPk_dnaw;
	 } 	  
       
        /**
	   * 属性voperid的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getVoperid() {
		 return voperid;
	  }   
	  
     /**
	   * 属性voperid的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newVoperid String
	   */
	public void setVoperid(String newVoperid) {
		
		voperid = newVoperid;
	 } 	  
       
        /**
	   * 属性voperdate的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return UFDate
	   */
	 public UFDate getVoperdate() {
		 return voperdate;
	  }   
	  
     /**
	   * 属性voperdate的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newVoperdate UFDate
	   */
	public void setVoperdate(UFDate newVoperdate) {
		
		voperdate = newVoperdate;
	 } 	  
       
        /**
	   * 属性pdu_no的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getPdu_no() {
		 return pdu_no;
	  }   
	  
     /**
	   * 属性pdu_no的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newPdu_no String
	   */
	public void setPdu_no(String newPdu_no) {
		
		pdu_no = newPdu_no;
	 } 	  
       
        /**
	   * 属性vemo的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getVemo() {
		 return vemo;
	  }   
	  
     /**
	   * 属性vemo的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newVemo String
	   */
	public void setVemo(String newVemo) {
		
		vemo = newVemo;
	 } 	  
       
        /**
	   * 属性dhpdu_flag的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return Integer
	   */
	 public Integer getDhpdu_flag() {
		 return dhpdu_flag;
	  }   
	  
     /**
	   * 属性dhpdu_flag的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newDhpdu_flag Integer
	   */
	public void setDhpdu_flag(Integer newDhpdu_flag) {
		
		dhpdu_flag = newDhpdu_flag;
	 } 	  
       
        /**
	   * 属性caiwuid的Getter方法.
	   *
	   * 创建日期:2014-7-7
	   * @return String
	   */
	 public String getCaiwuid() {
		 return caiwuid;
	  }   
	  
     /**
	   * 属性caiwuid的Setter方法.
	   *
	   * 创建日期:2014-7-7
	   * @param newCaiwuid String
	   */
	public void setCaiwuid(String newCaiwuid) {
		
		caiwuid = newCaiwuid;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-7-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_dhpdu == null) {
			errFields.add(new String("pk_dhpdu"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-7-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-7-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_dhpdu";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-7-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_product";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-7-7
	  */
	public PdutVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-7-7
	 * @param newPk_dhpdu 主键值
	 */
	 public PdutVO(String newPk_dhpdu) {
		
		// 为主键字段赋值:
		 pk_dhpdu = newPk_dhpdu;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-7-7
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_dhpdu;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-7-7
	  * @param newPk_dhpdu  String    
	  */
	 public void setPrimaryKey(String newPk_dhpdu) {
				
				pk_dhpdu = newPk_dhpdu; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-7-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_product"; 
				
	 } 
} 
