/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.dahuan.htlogo;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2013-10-6
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class ConLogoLSVO extends SuperVO {

	public String pk_corp;
	public String vdef4;
	public String pk_cust1;
	public String pk_fzr;
	public String pk_cttype;
	public String vdef7;
	public String ctcode;
	public String voperatorid;
	public String pk_skfs;
	public String vapprovenote;
	public String pk_billtype;
	public Integer vbillstatus;
	public String vmen;
	public String vdef2;
	public String vsourcebilltype;
	public UFDateTime tmodifytime;
	public String pk_busitype;
	public String vdef1;
	public String vjhaddress;
	public UFDate dstartdate;
	public UFDouble dctjetotal;
	public UFDate dbilldate;
	public String vbillno;
	public String pk_conlogols;
	public UFDate djhdate;
	public String pk_deptdoc;
	public String vlastbilltype;
	public String pk_jobmandoc;
	public String vdef3;
	public String vdef9;
	public UFDate dapprovedate;
	public String vdef8;
	public String pk_cust2;
	public String vlastbillid;
	public String vapproveid;
	public String vdef6;
	public UFDouble dcaigtotal;
	public String vdef10;
	public String vsourcebillid;
	public String vdef5;
	public UFDouble dsaletotal;
	public String ctname;
	public String cmodifyid;
	public String jobtype;
	public String custname1;
	public String custname2;
	public String htaddress;
	public Integer httype;
	public UFDate htrq;
	public String jobcode;
	public UFDouble ljfkjhje;
	public UFDouble ljsjfkje;
	   public UFDateTime ts;
       public Integer dr;
       public Integer is_delivery;
       public Integer is_seal;
       public Integer is_pay;
       public String pk_bank;
       public String pk_xmjl;
       public String sax_no;
       public String pk_ysid;
       public String ys_flag;
       public String pk_fuzong;
       public String fuzong_flag;

	
       
       
	public String getCmodifyid() {
		return cmodifyid;
	}

	public void setCmodifyid(String cmodifyid) {
		this.cmodifyid = cmodifyid;
	}

	public String getCtcode() {
		return ctcode;
	}

	public void setCtcode(String ctcode) {
		this.ctcode = ctcode;
	}

	public String getCtname() {
		return ctname;
	}

	public void setCtname(String ctname) {
		this.ctname = ctname;
	}

	public String getCustname1() {
		return custname1;
	}

	public void setCustname1(String custname1) {
		this.custname1 = custname1;
	}

	public String getCustname2() {
		return custname2;
	}

	public void setCustname2(String custname2) {
		this.custname2 = custname2;
	}

	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}

	public UFDate getDbilldate() {
		return dbilldate;
	}

	public void setDbilldate(UFDate dbilldate) {
		this.dbilldate = dbilldate;
	}

	public UFDouble getDcaigtotal() {
		return dcaigtotal;
	}

	public void setDcaigtotal(UFDouble dcaigtotal) {
		this.dcaigtotal = dcaigtotal;
	}

	public UFDouble getDctjetotal() {
		return dctjetotal;
	}

	public void setDctjetotal(UFDouble dctjetotal) {
		this.dctjetotal = dctjetotal;
	}

	public UFDate getDjhdate() {
		return djhdate;
	}

	public void setDjhdate(UFDate djhdate) {
		this.djhdate = djhdate;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDouble getDsaletotal() {
		return dsaletotal;
	}

	public void setDsaletotal(UFDouble dsaletotal) {
		this.dsaletotal = dsaletotal;
	}

	public UFDate getDstartdate() {
		return dstartdate;
	}

	public void setDstartdate(UFDate dstartdate) {
		this.dstartdate = dstartdate;
	}

	public String getFuzong_flag() {
		return fuzong_flag;
	}

	public void setFuzong_flag(String fuzong_flag) {
		this.fuzong_flag = fuzong_flag;
	}

	public String getHtaddress() {
		return htaddress;
	}

	public void setHtaddress(String htaddress) {
		this.htaddress = htaddress;
	}

	public UFDate getHtrq() {
		return htrq;
	}

	public void setHtrq(UFDate htrq) {
		this.htrq = htrq;
	}

	public Integer getHttype() {
		return httype;
	}

	public void setHttype(Integer httype) {
		this.httype = httype;
	}

	public Integer getIs_delivery() {
		return is_delivery;
	}

	public void setIs_delivery(Integer is_delivery) {
		this.is_delivery = is_delivery;
	}

	public Integer getIs_pay() {
		return is_pay;
	}

	public void setIs_pay(Integer is_pay) {
		this.is_pay = is_pay;
	}

	public Integer getIs_seal() {
		return is_seal;
	}

	public void setIs_seal(Integer is_seal) {
		this.is_seal = is_seal;
	}

	public String getJobcode() {
		return jobcode;
	}

	public void setJobcode(String jobcode) {
		this.jobcode = jobcode;
	}

	public String getJobtype() {
		return jobtype;
	}

	public void setJobtype(String jobtype) {
		this.jobtype = jobtype;
	}

	public UFDouble getLjfkjhje() {
		return ljfkjhje;
	}

	public void setLjfkjhje(UFDouble ljfkjhje) {
		this.ljfkjhje = ljfkjhje;
	}

	public UFDouble getLjsjfkje() {
		return ljsjfkje;
	}

	public void setLjsjfkje(UFDouble ljsjfkje) {
		this.ljsjfkje = ljsjfkje;
	}

	public String getPk_bank() {
		return pk_bank;
	}

	public void setPk_bank(String pk_bank) {
		this.pk_bank = pk_bank;
	}

	public String getPk_billtype() {
		return pk_billtype;
	}

	public void setPk_billtype(String pk_billtype) {
		this.pk_billtype = pk_billtype;
	}

	public String getPk_busitype() {
		return pk_busitype;
	}

	public void setPk_busitype(String pk_busitype) {
		this.pk_busitype = pk_busitype;
	}

	public String getPk_conlogols() {
		return pk_conlogols;
	}

	public void setPk_conlogols(String pk_conlogols) {
		this.pk_conlogols = pk_conlogols;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getPk_cttype() {
		return pk_cttype;
	}

	public void setPk_cttype(String pk_cttype) {
		this.pk_cttype = pk_cttype;
	}

	public String getPk_cust1() {
		return pk_cust1;
	}

	public void setPk_cust1(String pk_cust1) {
		this.pk_cust1 = pk_cust1;
	}

	public String getPk_cust2() {
		return pk_cust2;
	}

	public void setPk_cust2(String pk_cust2) {
		this.pk_cust2 = pk_cust2;
	}

	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	public void setPk_deptdoc(String pk_deptdoc) {
		this.pk_deptdoc = pk_deptdoc;
	}

	public String getPk_fuzong() {
		return pk_fuzong;
	}

	public void setPk_fuzong(String pk_fuzong) {
		this.pk_fuzong = pk_fuzong;
	}

	public String getPk_fzr() {
		return pk_fzr;
	}

	public void setPk_fzr(String pk_fzr) {
		this.pk_fzr = pk_fzr;
	}

	public String getPk_jobmandoc() {
		return pk_jobmandoc;
	}

	public void setPk_jobmandoc(String pk_jobmandoc) {
		this.pk_jobmandoc = pk_jobmandoc;
	}

	public String getPk_skfs() {
		return pk_skfs;
	}

	public void setPk_skfs(String pk_skfs) {
		this.pk_skfs = pk_skfs;
	}

	public String getPk_xmjl() {
		return pk_xmjl;
	}

	public void setPk_xmjl(String pk_xmjl) {
		this.pk_xmjl = pk_xmjl;
	}

	public String getPk_ysid() {
		return pk_ysid;
	}

	public void setPk_ysid(String pk_ysid) {
		this.pk_ysid = pk_ysid;
	}

	public String getSax_no() {
		return sax_no;
	}

	public void setSax_no(String sax_no) {
		this.sax_no = sax_no;
	}

	public UFDateTime getTmodifytime() {
		return tmodifytime;
	}

	public void setTmodifytime(UFDateTime tmodifytime) {
		this.tmodifytime = tmodifytime;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getVapproveid() {
		return vapproveid;
	}

	public void setVapproveid(String vapproveid) {
		this.vapproveid = vapproveid;
	}

	public String getVapprovenote() {
		return vapprovenote;
	}

	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}

	public String getVbillno() {
		return vbillno;
	}

	public void setVbillno(String vbillno) {
		this.vbillno = vbillno;
	}

	public Integer getVbillstatus() {
		return vbillstatus;
	}

	public void setVbillstatus(Integer vbillstatus) {
		this.vbillstatus = vbillstatus;
	}

	public String getVdef1() {
		return vdef1;
	}

	public void setVdef1(String vdef1) {
		this.vdef1 = vdef1;
	}

	public String getVdef10() {
		return vdef10;
	}

	public void setVdef10(String vdef10) {
		this.vdef10 = vdef10;
	}

	public String getVdef2() {
		return vdef2;
	}

	public void setVdef2(String vdef2) {
		this.vdef2 = vdef2;
	}

	public String getVdef3() {
		return vdef3;
	}

	public void setVdef3(String vdef3) {
		this.vdef3 = vdef3;
	}

	public String getVdef4() {
		return vdef4;
	}

	public void setVdef4(String vdef4) {
		this.vdef4 = vdef4;
	}

	public String getVdef5() {
		return vdef5;
	}

	public void setVdef5(String vdef5) {
		this.vdef5 = vdef5;
	}

	public String getVdef6() {
		return vdef6;
	}

	public void setVdef6(String vdef6) {
		this.vdef6 = vdef6;
	}

	public String getVdef7() {
		return vdef7;
	}

	public void setVdef7(String vdef7) {
		this.vdef7 = vdef7;
	}

	public String getVdef8() {
		return vdef8;
	}

	public void setVdef8(String vdef8) {
		this.vdef8 = vdef8;
	}

	public String getVdef9() {
		return vdef9;
	}

	public void setVdef9(String vdef9) {
		this.vdef9 = vdef9;
	}

	public String getVjhaddress() {
		return vjhaddress;
	}

	public void setVjhaddress(String vjhaddress) {
		this.vjhaddress = vjhaddress;
	}

	public String getVlastbillid() {
		return vlastbillid;
	}

	public void setVlastbillid(String vlastbillid) {
		this.vlastbillid = vlastbillid;
	}

	public String getVlastbilltype() {
		return vlastbilltype;
	}

	public void setVlastbilltype(String vlastbilltype) {
		this.vlastbilltype = vlastbilltype;
	}

	public String getVmen() {
		return vmen;
	}

	public void setVmen(String vmen) {
		this.vmen = vmen;
	}

	public String getVoperatorid() {
		return voperatorid;
	}

	public void setVoperatorid(String voperatorid) {
		this.voperatorid = voperatorid;
	}

	public String getVsourcebillid() {
		return vsourcebillid;
	}

	public void setVsourcebillid(String vsourcebillid) {
		this.vsourcebillid = vsourcebillid;
	}

	public String getVsourcebilltype() {
		return vsourcebilltype;
	}

	public void setVsourcebilltype(String vsourcebilltype) {
		this.vsourcebilltype = vsourcebilltype;
	}

	public String getYs_flag() {
		return ys_flag;
	}

	public void setYs_flag(String ys_flag) {
		this.ys_flag = ys_flag;
	}

	/**
	  * <p>取得父VO主键字段.
	 * <p>
	 * 创建日期:2013-10-6
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "";

	}

	/**
	  * <p>取得表主键.
	 * <p>
	 * 创建日期:2013-10-6
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_conlogols";
	}

	/**
      * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-10-6
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "dh_conlogols";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2013-10-6
	 */
	public ConLogoLSVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2013-10-6
	 * @param newPk_conlogols 主键值
	 */
	public ConLogoLSVO(String newPk_conlogols) {

		// 为主键字段赋值:
		pk_conlogols = newPk_conlogols;

	}

     
	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2013-10-6
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_conlogols;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2013-10-6
	  * @param newPk_conlogols  String    
	 */
	public void setPrimaryKey(String newPk_conlogols) {

		pk_conlogols = newPk_conlogols;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2013-10-6
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "dh_conlogols";

	}

}
