  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.ctInfo;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-7-2
 * @author author
 * @version Your Project 1.0
 */
     public class CustVO extends SuperVO {
           
             public String pk_dhcust;
             public Integer dhcust_type;
             public Integer dhcust_flag;
             public String dhcust_name;
             public String dhcust_shortname;
             public String dhcust_tel;
             public String dhcust_area;
             public String dhcust_pos;
             public String dhcust_bank;
             public String dhcust_sayno;
             public String dhcust_saxno;
             public String dhcust_vemo;
             public String voperid;
             public UFDate voperdate;
             public String fuzongid;
             public UFDate vappdate;
             public String caiwuid;
             public UFDate suredate;
             public UFDateTime ts;
             public Integer dr = 0;
             public String ret_vemo;
             public Integer dj_status;
             
             public String zuce_no;
             public UFDouble zuce_amount;
             public String qiye_type;
             public String cust_address;
             public String gcbid;
             public UFDate gcbdate;
             public String pkcumandoc;
             public String pk_cubasdoc;
             public String pk_accbank;
             public String pk_corp;
            
             public static final String  PK_DHCUST="pk_dhcust";   
             public static final String  DHCUST_SAXNO="dhcust_saxno";   
             public static final String  DHCUST_TYPE="dhcust_type";   
             public static final String  SUREDATE="suredate";   
             public static final String  VAPPDATE="vappdate";   
             public static final String  DHCUST_FLAG="dhcust_flag";   
             public static final String  FUZONGID="fuzongid";   
             public static final String  DHCUST_SHORTNAME="dhcust_shortname";   
             public static final String  DHCUST_TEL="dhcust_tel";   
             public static final String  DHCUST_NAME="dhcust_name";   
             public static final String  DHCUST_SAYNO="dhcust_sayno";   
             public static final String  DHCUST_BANK="dhcust_bank";   
             public static final String  DHCUST_VEMO="dhcust_vemo";   
             public static final String  VOPERID="voperid";   
             public static final String  VOPERDATE="voperdate";   
             public static final String  DHCUST_AREA="dhcust_area";   
             public static final String  DHCUST_POS="dhcust_pos";   
             public static final String  CAIWUID="caiwuid";   
      
             
             
        public String getPk_corp() {
				return pk_corp;
			}

			public void setPk_corp(String pk_corp) {
				this.pk_corp = pk_corp;
			}

		public String getPk_accbank() {
				return pk_accbank;
			}

			public void setPk_accbank(String pk_accbank) {
				this.pk_accbank = pk_accbank;
			}

			public String getPk_cubasdoc() {
				return pk_cubasdoc;
			}

			public void setPk_cubasdoc(String pk_cubasdoc) {
				this.pk_cubasdoc = pk_cubasdoc;
			}

		public String getPkcumandoc() {
				return pkcumandoc;
			}

			public void setPkcumandoc(String pkcumandoc) {
				this.pkcumandoc = pkcumandoc;
			}

		public Integer getDj_status() {
				return dj_status;
			}

			public void setDj_status(Integer dj_status) {
				this.dj_status = dj_status;
			}

		public String getCust_address() {
				return cust_address;
			}

			public void setCust_address(String cust_address) {
				this.cust_address = cust_address;
			}

			public UFDate getGcbdate() {
				return gcbdate;
			}

			public void setGcbdate(UFDate gcbdate) {
				this.gcbdate = gcbdate;
			}

			public String getGcbid() {
				return gcbid;
			}

			public void setGcbid(String gcbid) {
				this.gcbid = gcbid;
			}

			public String getQiye_type() {
				return qiye_type;
			}

			public void setQiye_type(String qiye_type) {
				this.qiye_type = qiye_type;
			}

			public UFDouble getZuce_amount() {
				return zuce_amount;
			}

			public void setZuce_amount(UFDouble zuce_amount) {
				this.zuce_amount = zuce_amount;
			}

			public String getZuce_no() {
				return zuce_no;
			}

			public void setZuce_no(String zuce_no) {
				this.zuce_no = zuce_no;
			}

		public String getRet_vemo() {
				return ret_vemo;
			}

			public void setRet_vemo(String ret_vemo) {
				this.ret_vemo = ret_vemo;
			}

		public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

		/**
	   * 属性pk_dhcust的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getPk_dhcust() {
		 return pk_dhcust;
	  }   
	  
     /**
	   * 属性pk_dhcust的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newPk_dhcust String
	   */
	public void setPk_dhcust(String newPk_dhcust) {
		
		pk_dhcust = newPk_dhcust;
	 } 	  
       
        /**
	   * 属性dhcust_saxno的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_saxno() {
		 return dhcust_saxno;
	  }   
	  
     /**
	   * 属性dhcust_saxno的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_saxno String
	   */
	public void setDhcust_saxno(String newDhcust_saxno) {
		
		dhcust_saxno = newDhcust_saxno;
	 } 	  
       
        /**
	   * 属性dhcust_type的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return Integer
	   */
	 public Integer getDhcust_type() {
		 return dhcust_type;
	  }   
	  
     /**
	   * 属性dhcust_type的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_type Integer
	   */
	public void setDhcust_type(Integer newDhcust_type) {
		
		dhcust_type = newDhcust_type;
	 } 	  
       
        /**
	   * 属性suredate的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return UFDate
	   */
	 public UFDate getSuredate() {
		 return suredate;
	  }   
	  
     /**
	   * 属性suredate的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newSuredate UFDate
	   */
	public void setSuredate(UFDate newSuredate) {
		
		suredate = newSuredate;
	 } 	  
       
        /**
	   * 属性vappdate的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return UFDate
	   */
	 public UFDate getVappdate() {
		 return vappdate;
	  }   
	  
     /**
	   * 属性vappdate的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newVappdate UFDate
	   */
	public void setVappdate(UFDate newVappdate) {
		
		vappdate = newVappdate;
	 } 	  
       
        /**
	   * 属性dhcust_flag的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return Integer
	   */
	 public Integer getDhcust_flag() {
		 return dhcust_flag;
	  }   
	  
     /**
	   * 属性dhcust_flag的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_flag Integer
	   */
	public void setDhcust_flag(Integer newDhcust_flag) {
		
		dhcust_flag = newDhcust_flag;
	 } 	  
       
        /**
	   * 属性fuzongid的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getFuzongid() {
		 return fuzongid;
	  }   
	  
     /**
	   * 属性fuzongid的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newFuzongid String
	   */
	public void setFuzongid(String newFuzongid) {
		
		fuzongid = newFuzongid;
	 } 	  
       
        /**
	   * 属性dhcust_shortname的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_shortname() {
		 return dhcust_shortname;
	  }   
	  
     /**
	   * 属性dhcust_shortname的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_shortname String
	   */
	public void setDhcust_shortname(String newDhcust_shortname) {
		
		dhcust_shortname = newDhcust_shortname;
	 } 	  
       
        /**
	   * 属性dhcust_tel的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_tel() {
		 return dhcust_tel;
	  }   
	  
     /**
	   * 属性dhcust_tel的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_tel String
	   */
	public void setDhcust_tel(String newDhcust_tel) {
		
		dhcust_tel = newDhcust_tel;
	 } 	  
       
        /**
	   * 属性dhcust_name的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_name() {
		 return dhcust_name;
	  }   
	  
     /**
	   * 属性dhcust_name的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_name String
	   */
	public void setDhcust_name(String newDhcust_name) {
		
		dhcust_name = newDhcust_name;
	 } 	  
       
        /**
	   * 属性dhcust_sayno的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_sayno() {
		 return dhcust_sayno;
	  }   
	  
     /**
	   * 属性dhcust_sayno的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_sayno String
	   */
	public void setDhcust_sayno(String newDhcust_sayno) {
		
		dhcust_sayno = newDhcust_sayno;
	 } 	  
       
        /**
	   * 属性dhcust_bank的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_bank() {
		 return dhcust_bank;
	  }   
	  
     /**
	   * 属性dhcust_bank的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_bank String
	   */
	public void setDhcust_bank(String newDhcust_bank) {
		
		dhcust_bank = newDhcust_bank;
	 } 	  
       
        /**
	   * 属性dhcust_vemo的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_vemo() {
		 return dhcust_vemo;
	  }   
	  
     /**
	   * 属性dhcust_vemo的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_vemo String
	   */
	public void setDhcust_vemo(String newDhcust_vemo) {
		
		dhcust_vemo = newDhcust_vemo;
	 } 	  
       
        /**
	   * 属性voperid的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getVoperid() {
		 return voperid;
	  }   
	  
     /**
	   * 属性voperid的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newVoperid String
	   */
	public void setVoperid(String newVoperid) {
		
		voperid = newVoperid;
	 } 	  
       
        /**
	   * 属性voperdate的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return UFDate
	   */
	 public UFDate getVoperdate() {
		 return voperdate;
	  }   
	  
     /**
	   * 属性voperdate的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newVoperdate UFDate
	   */
	public void setVoperdate(UFDate newVoperdate) {
		
		voperdate = newVoperdate;
	 } 	  
       
        /**
	   * 属性dhcust_area的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_area() {
		 return dhcust_area;
	  }   
	  
     /**
	   * 属性dhcust_area的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_area String
	   */
	public void setDhcust_area(String newDhcust_area) {
		
		dhcust_area = newDhcust_area;
	 } 	  
       
        /**
	   * 属性dhcust_pos的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getDhcust_pos() {
		 return dhcust_pos;
	  }   
	  
     /**
	   * 属性dhcust_pos的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newDhcust_pos String
	   */
	public void setDhcust_pos(String newDhcust_pos) {
		
		dhcust_pos = newDhcust_pos;
	 } 	  
       
        /**
	   * 属性caiwuid的Getter方法.
	   *
	   * 创建日期:2014-7-2
	   * @return String
	   */
	 public String getCaiwuid() {
		 return caiwuid;
	  }   
	  
     /**
	   * 属性caiwuid的Setter方法.
	   *
	   * 创建日期:2014-7-2
	   * @param newCaiwuid String
	   */
	public void setCaiwuid(String newCaiwuid) {
		
		caiwuid = newCaiwuid;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-7-2
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_dhcust == null) {
			errFields.add(new String("pk_dhcust"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-7-2
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-7-2
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_dhcust";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-7-2
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_customer";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-7-2
	  */
	public CustVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-7-2
	 * @param newPk_dhcust 主键值
	 */
	 public CustVO(String newPk_dhcust) {
		
		// 为主键字段赋值:
		 pk_dhcust = newPk_dhcust;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-7-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_dhcust;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-7-2
	  * @param newPk_dhcust  String    
	  */
	 public void setPrimaryKey(String newPk_dhcust) {
				
				pk_dhcust = newPk_dhcust; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-7-2
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_customer"; 
				
	 } 
} 
