  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fksq;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	

     public class DhFksqbillVO extends SuperVO {
           
             public UFDate dbilldate;
             public String vbillno;
             public String pk_corp;
             public String vprojectname;
             public UFDouble dfkje;
             public String vlastbilltype;
             public String ctcode;
             public String voperatorid;
             public String vapprovenote;
             public UFDate dapprovedate;
             public String pk_billtype;
             public Integer vbillstatus;
             public String vfkcontext;
             public String pk_cust2;
             public String vlastbillid;
             public String vapproveid;
             public String vsourcebilltype;
             public UFDateTime tmodifytime;
             public String pk_busitype;
             public UFDouble dfkbl;
             public String vsourcebillid;
             public String cmodifyid;
             public String pk_fksqbill;
             public UFDouble dctjetotal;
             public String pk_fkfs;
             public UFDateTime ts;
             public Integer dr;
             public String pk_deptdoc;
             public String pk_fzr;
             public UFDouble ljsfkje;
            
             public static final String  DBILLDATE="dbilldate";   
             public static final String  VBILLNO="vbillno";   
             public static final String  PK_CORP="pk_corp";   
             public static final String  VPROJECTNAME="vprojectname";   
             public static final String  DFKJE="dfkje";   
             public static final String  VLASTBILLTYPE="vlastbilltype";   
             public static final String  CTCODE="ctcode";   
             public static final String  VOPERATORID="voperatorid";   
             public static final String  VAPPROVENOTE="vapprovenote";   
             public static final String  DAPPROVEDATE="dapprovedate";   
             public static final String  PK_BILLTYPE="pk_billtype";   
             public static final String  VBILLSTATUS="vbillstatus";   
             public static final String  VFKCONTEXT="vfkcontext";   
             public static final String  PK_CUST2="pk_cust2";   
             public static final String  VLASTBILLID="vlastbillid";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  VSOURCEBILLTYPE="vsourcebilltype";   
             public static final String  TMODIFYTIME="tmodifytime";   
             public static final String  PK_BUSITYPE="pk_busitype";   
             public static final String  DFKBL="dfkbl";   
             public static final String  VSOURCEBILLID="vsourcebillid";   
             public static final String  CMODIFYID="cmodifyid";   
             public static final String  PK_FKSQBILL="pk_fksqbill";   
             public static final String  DCTJETOTAL="dctjetotal";   
      
    
        /**
	   * 属性dbilldate的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDate
	   */
	 public UFDate getDbilldate() {
		 return dbilldate;
	  }   
	  
     /**
	   * 属性dbilldate的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newDbilldate UFDate
	   */
	public void setDbilldate(UFDate newDbilldate) {
		
		dbilldate = newDbilldate;
	 } 	  
       
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性vprojectname的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVprojectname() {
		 return vprojectname;
	  }   
	  
     /**
	   * 属性vprojectname的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVprojectname String
	   */
	public void setVprojectname(String newVprojectname) {
		
		vprojectname = newVprojectname;
	 } 	  
       
        /**
	   * 属性dfkje的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDouble
	   */
	 public UFDouble getDfkje() {
		 return dfkje;
	  }   
	  
     /**
	   * 属性dfkje的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newDfkje UFDouble
	   */
	public void setDfkje(UFDouble newDfkje) {
		
		dfkje = newDfkje;
	 } 	  
       
        /**
	   * 属性vlastbilltype的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVlastbilltype() {
		 return vlastbilltype;
	  }   
	  
     /**
	   * 属性vlastbilltype的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVlastbilltype String
	   */
	public void setVlastbilltype(String newVlastbilltype) {
		
		vlastbilltype = newVlastbilltype;
	 } 	  
       
        /**
	   * 属性ctcode的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getCtcode() {
		 return ctcode;
	  }   
	  
     /**
	   * 属性ctcode的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newCtcode String
	   */
	public void setCtcode(String newCtcode) {
		
		ctcode = newCtcode;
	 } 	  
       
        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }   
	  
     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {
		
		voperatorid = newVoperatorid;
	 } 	  
       
        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }   
	  
     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {
		
		vapprovenote = newVapprovenote;
	 } 	  
       
        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }   
	  
     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {
		
		dapprovedate = newDapprovedate;
	 } 	  
       
        /**
	   * 属性pk_billtype的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getPk_billtype() {
		 return pk_billtype;
	  }   
	  
     /**
	   * 属性pk_billtype的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newPk_billtype String
	   */
	public void setPk_billtype(String newPk_billtype) {
		
		pk_billtype = newPk_billtype;
	 } 	  
       
        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }   
	  
     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {
		
		vbillstatus = newVbillstatus;
	 } 	  
       
        /**
	   * 属性vfkcontext的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVfkcontext() {
		 return vfkcontext;
	  }   
	  
     /**
	   * 属性vfkcontext的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVfkcontext String
	   */
	public void setVfkcontext(String newVfkcontext) {
		
		vfkcontext = newVfkcontext;
	 } 	  
       
        /**
	   * 属性pk_cust2的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getPk_cust2() {
		 return pk_cust2;
	  }   
	  
     /**
	   * 属性pk_cust2的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newPk_cust2 String
	   */
	public void setPk_cust2(String newPk_cust2) {
		
		pk_cust2 = newPk_cust2;
	 } 	  
       
        /**
	   * 属性vlastbillid的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVlastbillid() {
		 return vlastbillid;
	  }   
	  
     /**
	   * 属性vlastbillid的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVlastbillid String
	   */
	public void setVlastbillid(String newVlastbillid) {
		
		vlastbillid = newVlastbillid;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性vsourcebilltype的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVsourcebilltype() {
		 return vsourcebilltype;
	  }   
	  
     /**
	   * 属性vsourcebilltype的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVsourcebilltype String
	   */
	public void setVsourcebilltype(String newVsourcebilltype) {
		
		vsourcebilltype = newVsourcebilltype;
	 } 	  
       
        /**
	   * 属性tmodifytime的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDateTime
	   */
	 public UFDateTime getTmodifytime() {
		 return tmodifytime;
	  }   
	  
     /**
	   * 属性tmodifytime的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newTmodifytime UFDateTime
	   */
	public void setTmodifytime(UFDateTime newTmodifytime) {
		
		tmodifytime = newTmodifytime;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性dfkbl的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDouble
	   */
	 public UFDouble getDfkbl() {
		 return dfkbl;
	  }   
	  
     /**
	   * 属性dfkbl的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newDfkbl UFDouble
	   */
	public void setDfkbl(UFDouble newDfkbl) {
		
		dfkbl = newDfkbl;
	 } 	  
       
        /**
	   * 属性vsourcebillid的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getVsourcebillid() {
		 return vsourcebillid;
	  }   
	  
     /**
	   * 属性vsourcebillid的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newVsourcebillid String
	   */
	public void setVsourcebillid(String newVsourcebillid) {
		
		vsourcebillid = newVsourcebillid;
	 } 	  
       
        /**
	   * 属性cmodifyid的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getCmodifyid() {
		 return cmodifyid;
	  }   
	  
     /**
	   * 属性cmodifyid的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newCmodifyid String
	   */
	public void setCmodifyid(String newCmodifyid) {
		
		cmodifyid = newCmodifyid;
	 } 	  
       
        /**
	   * 属性pk_fksqbill的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return String
	   */
	 public String getPk_fksqbill() {
		 return pk_fksqbill;
	  }   
	  
     /**
	   * 属性pk_fksqbill的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newPk_fksqbill String
	   */
	public void setPk_fksqbill(String newPk_fksqbill) {
		
		pk_fksqbill = newPk_fksqbill;
	 } 	  
       
        /**
	   * 属性dctjetotal的Getter方法.
	   *
	   * 创建日期:2013-10-8
	   * @return UFDouble
	   */
	 public UFDouble getDctjetotal() {
		 return dctjetotal;
	  }   
	  
     /**
	   * 属性dctjetotal的Setter方法.
	   *
	   * 创建日期:2013-10-8
	   * @param newDctjetotal UFDouble
	   */
	public void setDctjetotal(UFDouble newDctjetotal) {
		
		dctjetotal = newDctjetotal;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2013-10-8
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fksqbill == null) {
			errFields.add(new String("pk_fksqbill"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-8
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-8
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fksqbill";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-8
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fksqbill";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-8
	  */
	public DhFksqbillVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-8
	 * @param newPk_fksqbill 主键值
	 */
	 public DhFksqbillVO(String newPk_fksqbill) {
		
		// 为主键字段赋值:
		 pk_fksqbill = newPk_fksqbill;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-8
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fksqbill;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-8
	  * @param newPk_fksqbill  String    
	  */
	 public void setPrimaryKey(String newPk_fksqbill) {
				
				pk_fksqbill = newPk_fksqbill; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-8
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fksqbill"; 
				
	 }

	public String getPk_fkfs() {
		return pk_fkfs;
	}

	public void setPk_fkfs(String pk_fkfs) {
		this.pk_fkfs = pk_fkfs;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public UFDouble getLjsfkje() {
		return ljsfkje;
	}

	public void setLjsfkje(UFDouble ljsfkje) {
		this.ljsfkje = ljsfkje;
	}

	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	public void setPk_deptdoc(String pk_deptdoc) {
		this.pk_deptdoc = pk_deptdoc;
	}

	public String getPk_fzr() {
		return pk_fzr;
	}

	public void setPk_fzr(String pk_fzr) {
		this.pk_fzr = pk_fzr;
	} 
} 
