  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkprintquery;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-2-25
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkbdprintVO extends SuperVO {
           
             public String corp_name;
             public String say_no;
             public String pk_fkprint;
             public String fzname;
             public String say_type;
             public String say_corp;
             public String dept_master;
             public String say_bank;
             public String print_no;
             public String dept_name;
             public UFDate print_date;
             public String pk_fkbd;
             public String say_content;
             public String dept_saleman;
             public UFDouble amount_sum;
             public String htcode1;
        	 public UFDouble htamount1;
        	 public String htcode2;
        	 public UFDouble htamount2;
        	 public String htcode3;
        	 public UFDouble htamount3;
        	 public String htcode4;
        	 public UFDouble htamount4;
        	 public String htcode5;
        	 public UFDouble htamount5;
        	 public String htcode6;
        	 public UFDouble htamount6;
        	 public String htcode7;
        	 public UFDouble htamount7;
        	 public String htcode8;
        	 public UFDouble htamount8;
        	 public String htcode9;
        	 public UFDouble htamount9;
        	 public String htcode10;
        	 public UFDouble htamount10;
        	 public String say_content1;
        	 public String say_type1;
        	 public String say_content2;
        	 public String say_type2;
        	 public String say_content3;
        	 public String say_type3;
        	 public String say_content4;
        	 public String say_type4;
        	 public String say_content5;
        	 public String say_type5;
        	 public String say_content6;
        	 public String say_type6;
        	 public String say_content7;
        	 public String say_type7;
        	 public String say_content8;
        	 public String say_type8;
        	 public String say_content9;
        	 public String say_type9;
        	 public String say_content10;
        	 public String say_type10;
        	 public String pk_fkjhbill;
        	 
        	 
        	 public String cwname;
        	 
        	 
            
             public String getCwname() {
				return cwname;
			}

			public void setCwname(String cwname) {
				this.cwname = cwname;
			}

			public String getPk_fkjhbill() {
				return pk_fkjhbill;
			}

			public void setPk_fkjhbill(String pk_fkjhbill) {
				this.pk_fkjhbill = pk_fkjhbill;
			}

			public static final String  CORP_NAME="corp_name";   
             public static final String  SAY_NO="say_no";   
             public static final String  PK_FKPRINT="pk_fkprint";   
             public static final String  FZNAME="fzname";   
             public static final String  SAY_TYPE="say_type";   
             public static final String  SAY_CORP="say_corp";   
             public static final String  DEPT_MASTER="dept_master";   
             public static final String  SAY_BANK="say_bank";   
             public static final String  PRINT_NO="print_no";   
             public static final String  DEPT_NAME="dept_name";   
             public static final String  PRINT_DATE="print_date";   
             public static final String  PK_FKBD="pk_fkbd";   
             public static final String  SAY_CONTENT="say_content";   
             public static final String  DEPT_SALEMAN="dept_saleman";   
             public static final String  AMOUNT_SUM="amount_sum";  
             public static final String HTCODE1="htcode1";
        	 public static final String HTAMOUNT1="htamount1";
        	 public static final String HTCODE2="htcode2";
        	 public static final String HTAMOUNT2="htamount2";
        	 public static final String HTCODE3="htcode3";
        	 public static final String HTAMOUNT3="htamount3";
        	 public static final String HTCODE4="htcode4";
        	 public static final String HTAMOUNT4="htamount4";
        	 public static final String HTCODE5="htcode5";
        	 public static final String HTAMOUNT5="htamount5";
        	 public static final String HTCODE6="htcode6";
        	 public static final String HTAMOUNT6="htamount6";
        	 public static final String HTCODE7="htcode7";
        	 public static final String HTAMOUNT7="htamount7";
        	 public static final String HTCODE8="htcode8";
        	 public static final String HTAMOUNT8="htamount8";
        	 public static final String HTCODE9="htcode9";
        	 public static final String HTAMOUNT9="htamount9";
        	 public static final String HTCODE10="htcode10";
        	 public static final String HTAMOUNT10="htamount10";
        	 public static final String SAY_CONTENT1="say_content1";
        	 public static final String SAY_TYPE1="say_type1";
        	 public static final String SAY_CONTENT2="say_content2";
        	 public static final String SAY_TYPE2="say_type2";
        	 public static final String SAY_CONTENT3="say_content3";
        	 public static final String SAY_TYPE3="say_type3";
        	 public static final String SAY_CONTENT4="say_content4";
        	 public static final String SAY_TYPE4="say_type4";
        	 public static final String SAY_CONTENT5="say_content5";
        	 public static final String SAY_TYPE5="say_type5";
        	 public static final String SAY_CONTENT6="say_content6";
        	 public static final String SAY_TYPE6="say_type6";
        	 public static final String SAY_CONTENT7="say_content7";
        	 public static final String SAY_TYPE7="say_type7";
        	 public static final String SAY_CONTENT8="say_content8";
        	 public static final String SAY_TYPE8="say_type8";
        	 public static final String SAY_CONTENT9="say_content9";
        	 public static final String SAY_TYPE9="say_type9";
        	 public static final String SAY_CONTENT10="say_content10";
        	 public static final String SAY_TYPE10="say_type10";
        	 
    
        	 
        public String getSay_content1() {
				return say_content1;
			}

			public void setSay_content1(String say_content1) {
				this.say_content1 = say_content1;
			}

			public String getSay_content10() {
				return say_content10;
			}

			public void setSay_content10(String say_content10) {
				this.say_content10 = say_content10;
			}

			public String getSay_content2() {
				return say_content2;
			}

			public void setSay_content2(String say_content2) {
				this.say_content2 = say_content2;
			}

			public String getSay_content3() {
				return say_content3;
			}

			public void setSay_content3(String say_content3) {
				this.say_content3 = say_content3;
			}

			public String getSay_content4() {
				return say_content4;
			}

			public void setSay_content4(String say_content4) {
				this.say_content4 = say_content4;
			}

			public String getSay_content5() {
				return say_content5;
			}

			public void setSay_content5(String say_content5) {
				this.say_content5 = say_content5;
			}

			public String getSay_content6() {
				return say_content6;
			}

			public void setSay_content6(String say_content6) {
				this.say_content6 = say_content6;
			}

			public String getSay_content7() {
				return say_content7;
			}

			public void setSay_content7(String say_content7) {
				this.say_content7 = say_content7;
			}

			public String getSay_content8() {
				return say_content8;
			}

			public void setSay_content8(String say_content8) {
				this.say_content8 = say_content8;
			}

			public String getSay_content9() {
				return say_content9;
			}

			public void setSay_content9(String say_content9) {
				this.say_content9 = say_content9;
			}

			public String getSay_type1() {
				return say_type1;
			}

			public void setSay_type1(String say_type1) {
				this.say_type1 = say_type1;
			}

			public String getSay_type10() {
				return say_type10;
			}

			public void setSay_type10(String say_type10) {
				this.say_type10 = say_type10;
			}

			public String getSay_type2() {
				return say_type2;
			}

			public void setSay_type2(String say_type2) {
				this.say_type2 = say_type2;
			}

			public String getSay_type3() {
				return say_type3;
			}

			public void setSay_type3(String say_type3) {
				this.say_type3 = say_type3;
			}

			public String getSay_type4() {
				return say_type4;
			}

			public void setSay_type4(String say_type4) {
				this.say_type4 = say_type4;
			}

			public String getSay_type5() {
				return say_type5;
			}

			public void setSay_type5(String say_type5) {
				this.say_type5 = say_type5;
			}

			public String getSay_type6() {
				return say_type6;
			}

			public void setSay_type6(String say_type6) {
				this.say_type6 = say_type6;
			}

			public String getSay_type7() {
				return say_type7;
			}

			public void setSay_type7(String say_type7) {
				this.say_type7 = say_type7;
			}

			public String getSay_type8() {
				return say_type8;
			}

			public void setSay_type8(String say_type8) {
				this.say_type8 = say_type8;
			}

			public String getSay_type9() {
				return say_type9;
			}

			public void setSay_type9(String say_type9) {
				this.say_type9 = say_type9;
			}

		public UFDouble getHtamount1() {
				return htamount1;
			}

			public void setHtamount1(UFDouble htamount1) {
				this.htamount1 = htamount1;
			}

			public UFDouble getHtamount10() {
				return htamount10;
			}

			public void setHtamount10(UFDouble htamount10) {
				this.htamount10 = htamount10;
			}

			public UFDouble getHtamount2() {
				return htamount2;
			}

			public void setHtamount2(UFDouble htamount2) {
				this.htamount2 = htamount2;
			}

			public UFDouble getHtamount3() {
				return htamount3;
			}

			public void setHtamount3(UFDouble htamount3) {
				this.htamount3 = htamount3;
			}

			public UFDouble getHtamount4() {
				return htamount4;
			}

			public void setHtamount4(UFDouble htamount4) {
				this.htamount4 = htamount4;
			}

			public UFDouble getHtamount5() {
				return htamount5;
			}

			public void setHtamount5(UFDouble htamount5) {
				this.htamount5 = htamount5;
			}

			public UFDouble getHtamount6() {
				return htamount6;
			}

			public void setHtamount6(UFDouble htamount6) {
				this.htamount6 = htamount6;
			}

			public UFDouble getHtamount7() {
				return htamount7;
			}

			public void setHtamount7(UFDouble htamount7) {
				this.htamount7 = htamount7;
			}

			public UFDouble getHtamount8() {
				return htamount8;
			}

			public void setHtamount8(UFDouble htamount8) {
				this.htamount8 = htamount8;
			}

			public UFDouble getHtamount9() {
				return htamount9;
			}

			public void setHtamount9(UFDouble htamount9) {
				this.htamount9 = htamount9;
			}

			public String getHtcode1() {
				return htcode1;
			}

			public void setHtcode1(String htcode1) {
				this.htcode1 = htcode1;
			}

			public String getHtcode10() {
				return htcode10;
			}

			public void setHtcode10(String htcode10) {
				this.htcode10 = htcode10;
			}

			public String getHtcode2() {
				return htcode2;
			}

			public void setHtcode2(String htcode2) {
				this.htcode2 = htcode2;
			}

			public String getHtcode3() {
				return htcode3;
			}

			public void setHtcode3(String htcode3) {
				this.htcode3 = htcode3;
			}

			public String getHtcode4() {
				return htcode4;
			}

			public void setHtcode4(String htcode4) {
				this.htcode4 = htcode4;
			}

			public String getHtcode5() {
				return htcode5;
			}

			public void setHtcode5(String htcode5) {
				this.htcode5 = htcode5;
			}

			public String getHtcode6() {
				return htcode6;
			}

			public void setHtcode6(String htcode6) {
				this.htcode6 = htcode6;
			}

			public String getHtcode7() {
				return htcode7;
			}

			public void setHtcode7(String htcode7) {
				this.htcode7 = htcode7;
			}

			public String getHtcode8() {
				return htcode8;
			}

			public void setHtcode8(String htcode8) {
				this.htcode8 = htcode8;
			}

			public String getHtcode9() {
				return htcode9;
			}

			public void setHtcode9(String htcode9) {
				this.htcode9 = htcode9;
			}

		/**
	   * 属性corp_name的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getCorp_name() {
		 return corp_name;
	  }   
	  
     /**
	   * 属性corp_name的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newCorp_name String
	   */
	public void setCorp_name(String newCorp_name) {
		
		corp_name = newCorp_name;
	 } 	  
       
        /**
	   * 属性say_no的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getSay_no() {
		 return say_no;
	  }   
	  
     /**
	   * 属性say_no的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newSay_no String
	   */
	public void setSay_no(String newSay_no) {
		
		say_no = newSay_no;
	 } 	  
       
        /**
	   * 属性pk_fkprint的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getPk_fkprint() {
		 return pk_fkprint;
	  }   
	  
     /**
	   * 属性pk_fkprint的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newPk_fkprint String
	   */
	public void setPk_fkprint(String newPk_fkprint) {
		
		pk_fkprint = newPk_fkprint;
	 } 	  
       
        /**
	   * 属性fzname的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getFzname() {
		 return fzname;
	  }   
	  
     /**
	   * 属性fzname的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newFzname String
	   */
	public void setFzname(String newFzname) {
		
		fzname = newFzname;
	 } 	  
       
        /**
	   * 属性say_type的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getSay_type() {
		 return say_type;
	  }   
	  
     /**
	   * 属性say_type的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newSay_type String
	   */
	public void setSay_type(String newSay_type) {
		
		say_type = newSay_type;
	 } 	  
       
        /**
	   * 属性say_corp的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getSay_corp() {
		 return say_corp;
	  }   
	  
     /**
	   * 属性say_corp的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newSay_corp String
	   */
	public void setSay_corp(String newSay_corp) {
		
		say_corp = newSay_corp;
	 } 	  
       
        /**
	   * 属性dept_master的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getDept_master() {
		 return dept_master;
	  }   
	  
     /**
	   * 属性dept_master的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newDept_master String
	   */
	public void setDept_master(String newDept_master) {
		
		dept_master = newDept_master;
	 } 	  
       
        /**
	   * 属性say_bank的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getSay_bank() {
		 return say_bank;
	  }   
	  
     /**
	   * 属性say_bank的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newSay_bank String
	   */
	public void setSay_bank(String newSay_bank) {
		
		say_bank = newSay_bank;
	 } 	  
       
        /**
	   * 属性print_no的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getPrint_no() {
		 return print_no;
	  }   
	  
     /**
	   * 属性print_no的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newPrint_no String
	   */
	public void setPrint_no(String newPrint_no) {
		
		print_no = newPrint_no;
	 } 	  
       
        /**
	   * 属性dept_name的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getDept_name() {
		 return dept_name;
	  }   
	  
     /**
	   * 属性dept_name的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newDept_name String
	   */
	public void setDept_name(String newDept_name) {
		
		dept_name = newDept_name;
	 } 	  
       
        /**
	   * 属性print_date的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return UFDate
	   */
	 public UFDate getPrint_date() {
		 return print_date;
	  }   
	  
     /**
	   * 属性print_date的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newPrint_date UFDate
	   */
	public void setPrint_date(UFDate newPrint_date) {
		
		print_date = newPrint_date;
	 } 	  
       
        /**
	   * 属性pk_fkbd的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getPk_fkbd() {
		 return pk_fkbd;
	  }   
	  
     /**
	   * 属性pk_fkbd的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newPk_fkbd String
	   */
	public void setPk_fkbd(String newPk_fkbd) {
		
		pk_fkbd = newPk_fkbd;
	 } 	  
       
        /**
	   * 属性say_content的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getSay_content() {
		 return say_content;
	  }   
	  
     /**
	   * 属性say_content的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newSay_content String
	   */
	public void setSay_content(String newSay_content) {
		
		say_content = newSay_content;
	 } 	  
       
        /**
	   * 属性dept_saleman的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return String
	   */
	 public String getDept_saleman() {
		 return dept_saleman;
	  }   
	  
     /**
	   * 属性dept_saleman的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newDept_saleman String
	   */
	public void setDept_saleman(String newDept_saleman) {
		
		dept_saleman = newDept_saleman;
	 } 	  
       
        /**
	   * 属性amount_sum的Getter方法.
	   *
	   * 创建日期:2014-2-25
	   * @return UFDouble
	   */
	 public UFDouble getAmount_sum() {
		 return amount_sum;
	  }   
	  
     /**
	   * 属性amount_sum的Setter方法.
	   *
	   * 创建日期:2014-2-25
	   * @param newAmount_sum UFDouble
	   */
	public void setAmount_sum(UFDouble newAmount_sum) {
		
		amount_sum = newAmount_sum;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-2-25
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fkbd == null) {
			errFields.add(new String("pk_fkbd"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-2-25
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-2-25
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkbd";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-2-25
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkbdprint";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-2-25
	  */
	public DhFkbdprintVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-2-25
	 * @param newPk_fkbd 主键值
	 */
	 public DhFkbdprintVO(String newPk_fkbd) {
		
		// 为主键字段赋值:
		 pk_fkbd = newPk_fkbd;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-2-25
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkbd;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-2-25
	  * @param newPk_fkbd  String    
	  */
	 public void setPrimaryKey(String newPk_fkbd) {
				
				pk_fkbd = newPk_fkbd; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-2-25
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkbdprint"; 
				
	 } 
} 
