  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fhtz;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-1-21
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhDeliveryDVO extends SuperVO {
           
             public String pduname;
             public String pk_dhdelivery;
             public String pk_product;
             public String pk_delivery_d;
             public UFDouble pdunum;
             public String stylemodel;
             public String remark;
             public Integer iscontract;
             public Integer dr;
             public UFDateTime ts;
             public UFDouble pduamount;
             public String model_no;
             public String pdunewname;
            
             public static final String  PDUNAME="pduname";   
             public static final String  PK_DELIVERY="pk_delivery";   
             public static final String  PK_PRODUCT="pk_product";   
             public static final String  PK_DELIVERY_D="pk_delivery_d";   
             public static final String  PDUNUM="pdunum";   
             public static final String  STYLEMODEL="stylemodel";   
             public static final String  REMARK="remark";   
             public static final String  ISCONTRACT="iscontract";   
             public static final String  DR="dr";   
             public static final String  TS="ts";   
      
             
    
        public String getPdunewname() {
				return pdunewname;
			}

			public void setPdunewname(String pdunewname) {
				this.pdunewname = pdunewname;
			}

		public String getModel_no() {
				return model_no;
			}

			public void setModel_no(String model_no) {
				this.model_no = model_no;
			}

		public UFDouble getPduamount() {
				return pduamount;
			}

			public void setPduamount(UFDouble pduamount) {
				this.pduamount = pduamount;
			}

		public Integer getDr() {
				return dr;
			}

			public void setDr(Integer dr) {
				this.dr = dr;
			}

			public Integer getIscontract() {
				return iscontract;
			}

			public void setIscontract(Integer iscontract) {
				this.iscontract = iscontract;
			}

			public UFDateTime getTs() {
				return ts;
			}

			public void setTs(UFDateTime ts) {
				this.ts = ts;
			}

		/**
	   * 属性pduname的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getPduname() {
		 return pduname;
	  }   
	  
     /**
	   * 属性pduname的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newPduname String
	   */
	public void setPduname(String newPduname) {
		
		pduname = newPduname;
	 } 	  
       
        /**
	   * 属性pk_delivery的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getPk_dhdelivery() {
		 return pk_dhdelivery;
	  }   
	  
     /**
	   * 属性pk_delivery的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newPk_delivery String
	   */
	public void setPk_dhdelivery(String newPk_dhdelivery) {
		
		pk_dhdelivery = newPk_dhdelivery;
	 } 	  
       
        /**
	   * 属性pk_product的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getPk_product() {
		 return pk_product;
	  }   
	  
     /**
	   * 属性pk_product的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newPk_product String
	   */
	public void setPk_product(String newPk_product) {
		
		pk_product = newPk_product;
	 } 	  
       
        /**
	   * 属性pk_delivery_d的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getPk_delivery_d() {
		 return pk_delivery_d;
	  }   
	  
     /**
	   * 属性pk_delivery_d的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newPk_delivery_d String
	   */
	public void setPk_delivery_d(String newPk_delivery_d) {
		
		pk_delivery_d = newPk_delivery_d;
	 } 	  
       
        /**
	   * 属性pdunum的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return Integer
	   */
	 public UFDouble getPdunum() {
		 return pdunum;
	  }   
	  
     /**
	   * 属性pdunum的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newPdunum Integer
	   */
	public void setPdunum(UFDouble newPdunum) {
		
		pdunum = newPdunum;
	 } 	  
       
        /**
	   * 属性stylemodel的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getStylemodel() {
		 return stylemodel;
	  }   
	  
     /**
	   * 属性stylemodel的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newStylemodel String
	   */
	public void setStylemodel(String newStylemodel) {
		
		stylemodel = newStylemodel;
	 } 	  
       
        /**
	   * 属性remark的Getter方法.
	   *
	   * 创建日期:2014-1-21
	   * @return String
	   */
	 public String getRemark() {
		 return remark;
	  }   
	  
     /**
	   * 属性remark的Setter方法.
	   *
	   * 创建日期:2014-1-21
	   * @param newRemark String
	   */
	public void setRemark(String newRemark) {
		
		remark = newRemark;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-1-21
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_delivery_d == null) {
			errFields.add(new String("pk_dhdelivery_d"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-1-21
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_dhdelivery";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-1-21
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_delivery_d";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-1-21
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_delivery_d";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-1-21
	  */
	public DhDeliveryDVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-1-21
	 * @param newPk_delivery_d 主键值
	 */
	 public DhDeliveryDVO(String newPk_delivery_d) {
		
		// 为主键字段赋值:
		 pk_delivery_d = newPk_delivery_d;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-21
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_delivery_d;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-21
	  * @param newPk_delivery_d  String    
	  */
	 public void setPrimaryKey(String newPk_delivery_d) {
				
				pk_delivery_d = newPk_delivery_d; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-1-21
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_delivery_d"; 
				
	 } 
} 
