  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dahuan.fkjh;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2013-10-31
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DhFkjhbillVO extends SuperVO {
           
             public UFDate dbilldate;
             public String vbillno;
             public String pk_corp;
             public String vprojectname;
             public UFDouble ljfkje;
             public UFDouble dfkje;
             public String pk_fkfs;
             public String ctcode;
             public String voperatorid;
             public String pk_fkjhbill;
             public String vapprovenote;
             public UFDate dapprovedate;
             public String pk_billtype;
             public Integer vbillstatus;
             public String vfkcontext;
             public String pk_cust2;
             public String vapproveid;
             public String vsourcebilltype;
             public String pk_busitype;
             public UFDouble dfkbl;
             public String vsourcebillid;
             public UFDouble dctjetotal;
             public String vyearmonth;
             public String jobcode;
             public String ctname;
             public String pk_deptdoc;
             public String pk_fzr;
             public String shr1;
             public String shr2;
             public String shr3;
             public String shr4;
             public String shr5;
             public String shr6;
             public Integer is_print=0;
             public Integer is_pay=0;
             public String pk_dept;
             public String pk_fkjhprint;
             public String pk_bank;
             public String say_no;
             public String cwid;
             public UFDate cwdate;
             public String cwflag="0";
             public String ret_user;
             public UFDate ret_date;
             public String pk_cttype;
             public Integer httype;
             
             public String qishenyuanyin;

             public String fknr;
             
			 public UFBoolean iffknr1;
             public UFBoolean iffknr2;
             public UFBoolean iffknr3;
             public UFBoolean iffknr4;
             public UFBoolean iffknr5;
             public UFBoolean iffknr6;
             
             public UFBoolean ifzffy1;
             public UFBoolean ifzffy2;
             public UFBoolean ifzffy3;
             public UFBoolean ifzffy4;
             public UFBoolean ifzffy5;
             public UFBoolean ifzffy6;
             public UFBoolean ifzffy7;
             public UFBoolean ifzffy8;
             public UFBoolean ifzffy9;
             
             
             public String shrid1;
             public UFDate shrdate1;
             public String shrflag1="0";
             public String shrid2;
             public UFDate shrdate2;
             public String shrflag2="0";
             public String shrid3;
             public UFDate shrdate3;
             public String shrflag3;
             public String shrid4;
             public UFDate shrdate4;
             public String shrflag4;
             public String voperatorflag="0";
             
             public UFDouble xmysk;
             
             public String fk_dept;
             
             public String print_no;
             
             public String pk_currenty;
              
             public UFDouble currenty_rate;
             
             public UFDouble currenty_amount;
             
             public Integer is_single=0;
             public String single_remark;
             
             public String relationid;
             public Integer is_relation;
             
             public UFDouble sjspje; //实际收票金额
             public Integer sealflag;
             public String sealid;
             public UFDate sealdate;
             
             
             public UFDate getSealdate() {
				return sealdate;
			}

			public void setSealdate(UFDate sealdate) {
				this.sealdate = sealdate;
			}

			public Integer getSealflag() {
				return sealflag;
			}

			public void setSealflag(Integer sealflag) {
				this.sealflag = sealflag;
			}

			public String getSealid() {
				return sealid;
			}

			public void setSealid(String sealid) {
				this.sealid = sealid;
			}

             public Integer getIs_relation() {
				return is_relation;
			}

			public void setIs_relation(Integer is_relation) {
				this.is_relation = is_relation;
			}

			public String getRelationid() {
				return relationid;
			}

			public void setRelationid(String relationid) {
				this.relationid = relationid;
			}

			public Integer getIs_single() {
				return is_single;
			}

			public void setIs_single(Integer is_single) {
				this.is_single = is_single;
			}

			public String getSingle_remark() {
				return single_remark;
			}

			public void setSingle_remark(String single_remark) {
				this.single_remark = single_remark;
			}

			public UFDouble getCurrenty_amount() {
				return currenty_amount;
			}

			public void setCurrenty_amount(UFDouble currenty_amount) {
				this.currenty_amount = currenty_amount;
			}

			public UFDouble getCurrenty_rate() {
				return currenty_rate;
			}

			public void setCurrenty_rate(UFDouble currenty_rate) {
				this.currenty_rate = currenty_rate;
			}

			public String getPk_currenty() {
				return pk_currenty;
			}

			public void setPk_currenty(String pk_currenty) {
				this.pk_currenty = pk_currenty;
			}

			public String getPrint_no() {
				return print_no;
			}

			public void setPrint_no(String print_no) {
				this.print_no = print_no;
			}

			public String getFknr() {
				return fknr;
			}

			public void setFknr(String fknr) {
				this.fknr = fknr;
			}

			public Integer getHttype() {
				return httype;
			}

			public void setHttype(Integer httype) {
				this.httype = httype;
			}

			public String getPk_cttype() {
				return pk_cttype;
			}

			public void setPk_cttype(String pk_cttype) {
				this.pk_cttype = pk_cttype;
			}

			public UFDate getRet_date() {
				return ret_date;
			}

			public void setRet_date(UFDate ret_date) {
				this.ret_date = ret_date;
			}

			public String getRet_user() {
				return ret_user;
			}

			public void setRet_user(String ret_user) {
				this.ret_user = ret_user;
			}

			public String getFk_dept() {
				return fk_dept;
			}

			public void setFk_dept(String fk_dept) {
				this.fk_dept = fk_dept;
			}

			public UFDouble getXmysk() {
				return xmysk;
			}

			public void setXmysk(UFDouble xmysk) {
				this.xmysk = xmysk;
			}

			public String getQishenyuanyin() {
				return qishenyuanyin;
			}

			public void setQishenyuanyin(String qishenyuanyin) {
				this.qishenyuanyin = qishenyuanyin;
			}

			public UFDate getCwdate() {
				return cwdate;
			}

			public void setCwdate(UFDate cwdate) {
				this.cwdate = cwdate;
			}

			public String getCwflag() {
				return cwflag;
			}

			public void setCwflag(String cwflag) {
				this.cwflag = cwflag;
			}

			public String getCwid() {
				return cwid;
			}

			public void setCwid(String cwid) {
				this.cwid = cwid;
			}

			public String getPk_bank() {
				return pk_bank;
			}

			public void setPk_bank(String pk_bank) {
				this.pk_bank = pk_bank;
			}

			public String getPk_fkjhprint() {
				return pk_fkjhprint;
			}

			public void setPk_fkjhprint(String pk_fkjhprint) {
				this.pk_fkjhprint = pk_fkjhprint;
			}

			public String getSay_no() {
				return say_no;
			}

			public void setSay_no(String say_no) {
				this.say_no = say_no;
			}

			public String getPk_dept() {
				return pk_dept;
			}

			public void setPk_dept(String pk_dept) {
				this.pk_dept = pk_dept;
			}

			public Integer getIs_pay() {
				return is_pay;
			}

			public void setIs_pay(Integer is_pay) {
				this.is_pay = is_pay;
			}

			public Integer getIs_print() {
				return is_print;
			}

			public void setIs_print(Integer is_print) {
				this.is_print = is_print;
			}

			public UFDate getShrdate1() {
				return shrdate1;
			}

			public void setShrdate1(UFDate shrdate1) {
				this.shrdate1 = shrdate1;
			}

			public UFDate getShrdate2() {
				return shrdate2;
			}

			public void setShrdate2(UFDate shrdate2) {
				this.shrdate2 = shrdate2;
			}

			public UFDate getShrdate3() {
				return shrdate3;
			}

			public void setShrdate3(UFDate shrdate3) {
				this.shrdate3 = shrdate3;
			}

			public UFDate getShrdate4() {
				return shrdate4;
			}

			public void setShrdate4(UFDate shrdate4) {
				this.shrdate4 = shrdate4;
			}

			public String getShrflag1() {
				return shrflag1;
			}

			public void setShrflag1(String shrflag1) {
				this.shrflag1 = shrflag1;
			}

			public String getShrflag2() {
				return shrflag2;
			}

			public void setShrflag2(String shrflag2) {
				this.shrflag2 = shrflag2;
			}

			public String getShrflag3() {
				return shrflag3;
			}

			public void setShrflag3(String shrflag3) {
				this.shrflag3 = shrflag3;
			}

			public String getShrflag4() {
				return shrflag4;
			}

			public void setShrflag4(String shrflag4) {
				this.shrflag4 = shrflag4;
			}

			public String getShrid1() {
				return shrid1;
			}

			public void setShrid1(String shrid1) {
				this.shrid1 = shrid1;
			}

			public String getShrid2() {
				return shrid2;
			}

			public void setShrid2(String shrid2) {
				this.shrid2 = shrid2;
			}

			public String getShrid3() {
				return shrid3;
			}

			public void setShrid3(String shrid3) {
				this.shrid3 = shrid3;
			}

			public String getShrid4() {
				return shrid4;
			}

			public void setShrid4(String shrid4) {
				this.shrid4 = shrid4;
			}

			public String getVoperatorflag() {
				return voperatorflag;
			}

			public void setVoperatorflag(String voperatorflag) {
				this.voperatorflag = voperatorflag;
			}

			public String getShr1() {
				return shr1;
			}

			public void setShr1(String shr1) {
				this.shr1 = shr1;
			}

			public String getShr2() {
				return shr2;
			}

			public void setShr2(String shr2) {
				this.shr2 = shr2;
			}

			public String getShr3() {
				return shr3;
			}

			public void setShr3(String shr3) {
				this.shr3 = shr3;
			}

			public String getShr4() {
				return shr4;
			}

			public void setShr4(String shr4) {
				this.shr4 = shr4;
			}

			public String getShr5() {
				return shr5;
			}

			public void setShr5(String shr5) {
				this.shr5 = shr5;
			}

			public String getShr6() {
				return shr6;
			}

			public void setShr6(String shr6) {
				this.shr6 = shr6;
			}
            
             public UFBoolean getIffknr1() {
				return iffknr1;
			}

			public void setIffknr1(UFBoolean iffknr1) {
				this.iffknr1 = iffknr1;
			}

			public UFBoolean getIffknr2() {
				return iffknr2;
			}

			public void setIffknr2(UFBoolean iffknr2) {
				this.iffknr2 = iffknr2;
			}

			public UFBoolean getIffknr3() {
				return iffknr3;
			}

			public void setIffknr3(UFBoolean iffknr3) {
				this.iffknr3 = iffknr3;
			}

			public UFBoolean getIffknr4() {
				return iffknr4;
			}

			public void setIffknr4(UFBoolean iffknr4) {
				this.iffknr4 = iffknr4;
			}

			public UFBoolean getIffknr5() {
				return iffknr5;
			}

			public void setIffknr5(UFBoolean iffknr5) {
				this.iffknr5 = iffknr5;
			}

			public UFBoolean getIffknr6() {
				return iffknr6;
			}

			public void setIffknr6(UFBoolean iffknr6) {
				this.iffknr6 = iffknr6;
			}

			public UFBoolean getIfzffy1() {
				return ifzffy1;
			}

			public void setIfzffy1(UFBoolean ifzffy1) {
				this.ifzffy1 = ifzffy1;
			}

			public UFBoolean getIfzffy2() {
				return ifzffy2;
			}

			public void setIfzffy2(UFBoolean ifzffy2) {
				this.ifzffy2 = ifzffy2;
			}

			public UFBoolean getIfzffy3() {
				return ifzffy3;
			}

			public void setIfzffy3(UFBoolean ifzffy3) {
				this.ifzffy3 = ifzffy3;
			}

			public UFBoolean getIfzffy4() {
				return ifzffy4;
			}

			public void setIfzffy4(UFBoolean ifzffy4) {
				this.ifzffy4 = ifzffy4;
			}

			public UFBoolean getIfzffy5() {
				return ifzffy5;
			}

			public void setIfzffy5(UFBoolean ifzffy5) {
				this.ifzffy5 = ifzffy5;
			}

			public UFBoolean getIfzffy6() {
				return ifzffy6;
			}

			public void setIfzffy6(UFBoolean ifzffy6) {
				this.ifzffy6 = ifzffy6;
			}

			public UFBoolean getIfzffy7() {
				return ifzffy7;
			}

			public void setIfzffy7(UFBoolean ifzffy7) {
				this.ifzffy7 = ifzffy7;
			}

			public UFBoolean getIfzffy8() {
				return ifzffy8;
			}

			public void setIfzffy8(UFBoolean ifzffy8) {
				this.ifzffy8 = ifzffy8;
			}

			public UFBoolean getIfzffy9() {
				return ifzffy9;
			}

			public void setIfzffy9(UFBoolean ifzffy9) {
				this.ifzffy9 = ifzffy9;
			}

			public static final String  DBILLDATE="dbilldate";   
             public static final String  VBILLNO="vbillno";   
             public static final String  PK_CORP="pk_corp";   
             public static final String  VPROJECTNAME="vprojectname";   
             public static final String  LJFKJE="ljfkje";   
             public static final String  DFKJE="dfkje";   
             public static final String  PK_FKFS="pk_fkfs";   
             public static final String  CTCODE="ctcode";   
             public static final String  VOPERATORID="voperatorid";   
             public static final String  PK_FKJHBILL="pk_fkjhbill";   
             public static final String  VAPPROVENOTE="vapprovenote";   
             public static final String  DAPPROVEDATE="dapprovedate";   
             public static final String  PK_BILLTYPE="pk_billtype";   
             public static final String  VBILLSTATUS="vbillstatus";   
             public static final String  VFKCONTEXT="vfkcontext";   
             public static final String  PK_CUST2="pk_cust2";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  VSOURCEBILLTYPE="vsourcebilltype";   
             public static final String  PK_BUSITYPE="pk_busitype";   
             public static final String  DFKBL="dfkbl";   
             public static final String  VSOURCEBILLID="vsourcebillid";   
             public static final String  DCTJETOTAL="dctjetotal";   
             
             public static final String SHRID1="shrid1";
             public static final String SHRDATE1="shrdate1";
             public static final String SHRFLAG1="shrflag1";
             public static final String SHRID2="shrid2";
             public static final String SHRDATE2="shrdate2";
             public static final String SHRFLAG2="shrflag2";
             public static final String SHRID3="shrid3";
             public static final String SHRDATE3="shrdate3";
             public static final String SHRFLAG3="shrflag3";
             public static final String SHRID4="shrid4";
             public static final String SHRDATE4="shrdate4";
             public static final String SHRFLAG4="shrflag4";
             public static final String VOPERATORFLAG="voperatorflag";
             public static final String  IS_PAY="is_pay";
             public static final String  IS_PRINT="is_print";
             public static final String  PK_DEPT="pk_dept";
             public static final String  PK_FKJHPRINT="pk_fkjhprint";
             public static final String  PK_BANK="pk_bank";
             public static final String  SAY_NO="say_no";
             public static final String  QISHENYUANYIN="qishenyuanyin";
             public static final String  XMYSK="xmysk";
    
        /**
	   * 属性dbilldate的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDate
	   */
	 public UFDate getDbilldate() {
		 return dbilldate;
	  }   
	  
     /**
	   * 属性dbilldate的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newDbilldate UFDate
	   */
	public void setDbilldate(UFDate newDbilldate) {
		
		dbilldate = newDbilldate;
	 } 	  
       
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性vprojectname的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVprojectname() {
		 return vprojectname;
	  }   
	  
     /**
	   * 属性vprojectname的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVprojectname String
	   */
	public void setVprojectname(String newVprojectname) {
		
		vprojectname = newVprojectname;
	 } 	  
       
        /**
	   * 属性ljfkje的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDouble
	   */
	 public UFDouble getLjfkje() {
		 return ljfkje;
	  }   
	  
     /**
	   * 属性ljfkje的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newLjfkje UFDouble
	   */
	public void setLjfkje(UFDouble newLjfkje) {
		
		ljfkje = newLjfkje;
	 } 	  
       
        /**
	   * 属性dfkje的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDouble
	   */
	 public UFDouble getDfkje() {
		 return dfkje;
	  }   
	  
     /**
	   * 属性dfkje的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newDfkje UFDouble
	   */
	public void setDfkje(UFDouble newDfkje) {
		
		dfkje = newDfkje;
	 } 	  
       
        /**
	   * 属性pk_fkfs的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_fkfs() {
		 return pk_fkfs;
	  }   
	  
     /**
	   * 属性pk_fkfs的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_fkfs String
	   */
	public void setPk_fkfs(String newPk_fkfs) {
		
		pk_fkfs = newPk_fkfs;
	 } 	  
       
        /**
	   * 属性ctcode的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getCtcode() {
		 return ctcode;
	  }   
	  
     /**
	   * 属性ctcode的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newCtcode String
	   */
	public void setCtcode(String newCtcode) {
		
		ctcode = newCtcode;
	 } 	  
       
        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }   
	  
     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {
		
		voperatorid = newVoperatorid;
	 } 	  
       
        /**
	   * 属性pk_fkjhbill的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_fkjhbill() {
		 return pk_fkjhbill;
	  }   
	  
     /**
	   * 属性pk_fkjhbill的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_fkjhbill String
	   */
	public void setPk_fkjhbill(String newPk_fkjhbill) {
		
		pk_fkjhbill = newPk_fkjhbill;
	 } 	  
       
        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }   
	  
     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {
		
		vapprovenote = newVapprovenote;
	 } 	  
       
        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }   
	  
     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {
		
		dapprovedate = newDapprovedate;
	 } 	  
       
        /**
	   * 属性pk_billtype的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_billtype() {
		 return pk_billtype;
	  }   
	  
     /**
	   * 属性pk_billtype的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_billtype String
	   */
	public void setPk_billtype(String newPk_billtype) {
		
		pk_billtype = newPk_billtype;
	 } 	  
       
        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }   
	  
     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {
		
		vbillstatus = newVbillstatus;
	 } 	  
       
        /**
	   * 属性vfkcontext的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVfkcontext() {
		 return vfkcontext;
	  }   
	  
     /**
	   * 属性vfkcontext的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVfkcontext String
	   */
	public void setVfkcontext(String newVfkcontext) {
		
		vfkcontext = newVfkcontext;
	 } 	  
       
        /**
	   * 属性pk_cust2的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_cust2() {
		 return pk_cust2;
	  }   
	  
     /**
	   * 属性pk_cust2的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_cust2 String
	   */
	public void setPk_cust2(String newPk_cust2) {
		
		pk_cust2 = newPk_cust2;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性vsourcebilltype的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVsourcebilltype() {
		 return vsourcebilltype;
	  }   
	  
     /**
	   * 属性vsourcebilltype的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVsourcebilltype String
	   */
	public void setVsourcebilltype(String newVsourcebilltype) {
		
		vsourcebilltype = newVsourcebilltype;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性dfkbl的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDouble
	   */
	 public UFDouble getDfkbl() {
		 return dfkbl;
	  }   
	  
     /**
	   * 属性dfkbl的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newDfkbl UFDouble
	   */
	public void setDfkbl(UFDouble newDfkbl) {
		
		dfkbl = newDfkbl;
	 } 	  
       
        /**
	   * 属性vsourcebillid的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return String
	   */
	 public String getVsourcebillid() {
		 return vsourcebillid;
	  }   
	  
     /**
	   * 属性vsourcebillid的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newVsourcebillid String
	   */
	public void setVsourcebillid(String newVsourcebillid) {
		
		vsourcebillid = newVsourcebillid;
	 } 	  
       
        /**
	   * 属性dctjetotal的Getter方法.
	   *
	   * 创建日期:2013-10-31
	   * @return UFDouble
	   */
	 public UFDouble getDctjetotal() {
		 return dctjetotal;
	  }   
	  
     /**
	   * 属性dctjetotal的Setter方法.
	   *
	   * 创建日期:2013-10-31
	   * @param newDctjetotal UFDouble
	   */
	public void setDctjetotal(UFDouble newDctjetotal) {
		
		dctjetotal = newDctjetotal;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2013-10-31
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_fkjhbill == null) {
			errFields.add(new String("pk_fkjhbill"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fkjhbill";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2013-10-31
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dh_fkjhbill";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-10-31
	  */
	public DhFkjhbillVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2013-10-31
	 * @param newPk_fkjhbill 主键值
	 */
	 public DhFkjhbillVO(String newPk_fkjhbill) {
		
		// 为主键字段赋值:
		 pk_fkjhbill = newPk_fkjhbill;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-31
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fkjhbill;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2013-10-31
	  * @param newPk_fkjhbill  String    
	  */
	 public void setPrimaryKey(String newPk_fkjhbill) {
				
				pk_fkjhbill = newPk_fkjhbill; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2013-10-31
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dh_fkjhbill"; 
				
	 }

	public String getVyearmonth() {
		return vyearmonth;
	}

	public void setVyearmonth(String vyearmonth) {
		this.vyearmonth = vyearmonth;
	}

	public String getJobcode() {
		return jobcode;
	}

	public void setJobcode(String jobcode) {
		this.jobcode = jobcode;
	}

	public String getCtname() {
		return ctname;
	}

	public void setCtname(String ctname) {
		this.ctname = ctname;
	}

	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	public void setPk_deptdoc(String pk_deptdoc) {
		this.pk_deptdoc = pk_deptdoc;
	}

	public String getPk_fzr() {
		return pk_fzr;
	}

	public void setPk_fzr(String pk_fzr) {
		this.pk_fzr = pk_fzr;
	}

	public UFDouble getSjspje() {
		return sjspje;
	}

	public void setSjspje(UFDouble sjspje) {
		this.sjspje = sjspje;
	} 
} 
